### ISSUE TITLE
java.lang.NoSuchMethodError: putMemberOffset

### ISSUE THREAD

**Issue by gwenn** [bytedeco/javacpp#104]
Regression between version 1.1 and 1.2.1:
```
java.lang.NoSuchMethodError: putMemberOffset
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1821)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:685)
	at org.bytedeco.javacpp.Loader.load(Loader.java:500)
	at org.bytedeco.javacpp.Loader.load(Loader.java:417)
	at org.sqlite.SQLite.<clinit>(SQLite.java:29)
	at org.sqlite.ConfigTest.shutdown(ConfigTest.java:12)
```
https://github.com/gwenn/sqlite-jna/blob/javacpp/pom.xml

**Comment by saudet** [comment]
Libraries between these two versions are not compatible:
http://bytedeco.org/news/2016/05/15/deeper-in-deep-learning/
You'll need to rebuild the binaries, but that's about it.
