### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: org/bytedeco/javacpp/avutil$AVFrame.

### ISSUE THREAD

**Issue by balajikaliappan** [bytedeco/javacpp#11]
Hi,
I'm trying to capture the png image from mp4 video Using ffmpegframegrabber and it works fine in Mac os but not in Linux server. I'm getting this error when I try to execute the code in the Linux server. please help

Thanks,
Balaji

**Comment by saudet** [comment]
Could you try running the `Demo` class using the `pom.xml` file and the `mvn` command given here:
https://github.com/bytedeco/javacv#sample-usage
And let me know what happens with that? Thanks!

**Comment by balajikaliappan** [comment]
Thanks for your reply!!

I get this below error when i execute the mvn command.

java.lang.reflect.InvocationTargetException

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)

at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)

at java.lang.reflect.Method.invoke(Method.java:597)

at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)

at java.lang.Thread.run(Thread.java:695)

Caused by: java.lang.UnsatisfiedLinkError: no jniopencv_core in
java.library.path

at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1764)

at java.lang.Runtime.loadLibrary0(Runtime.java:823)

at java.lang.System.loadLibrary(System.java:1044)

at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:535)

at org.bytedeco.javacpp.Loader.load(Loader.java:410)

at org.bytedeco.javacpp.Loader.load(Loader.java:353)

at org.bytedeco.javacpp.opencv_core.<clinit>(opencv_core.java:10)

at java.lang.Class.forName0(Native Method)

at java.lang.Class.forName(Class.java:249)

at org.bytedeco.javacpp.Loader.load(Loader.java:385)

at com.Nielsen.service.Demo.main(Demo.java:26)

... 6 more

Caused by: java.lang.UnsatisfiedLinkError: no opencv_core in
java.library.path

at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1764)

at java.lang.Runtime.loadLibrary0(Runtime.java:823)

at java.lang.System.loadLibrary(System.java:1044)

at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:535)

at org.bytedeco.javacpp.Loader.load(Loader.java:401)

... 12 more

Please find the attached pom.xml file.

PS: Im running the mvn command from Mac terminal.

Thanks,

Balaji

**Comment by saudet** [comment]
What are you using as command line options for `mvn`?

**Comment by balajikaliappan** [comment]
This the comand I have used.

$ mvn package exec:java -Dplatform.dependencies
-Dexec.mainClass=com.service.Demo.

Thanks,
Balaji

**Comment by saudet** [comment]
And what happens if you run that from Linux?

**Comment by balajikaliappan** [comment]
I didn't try it yet.

Do I need to copy any jars in my class path ?

This is what I have done.
Created my own class and demo class.
Crested the pom which I sent you.

Ran the mvn command. Please let me know if Is it correct or do I need to
add any jars in my classpath.

Thanks,
Balaji

**Comment by saudet** [comment]
You did not send any `pom.xml` file.

You said you had a problem on Linux, but now you say you cannot run it on Linux, so I'm not sure what the problem is. If you can clarify what the problem is, please provide more information about your environment, etc.

**Comment by balajikaliappan** [comment]
I had sent the pom file in my previous mail and I had told that I'm
running  from the mac but the actual problem is when I run the code in the
Linux.

Please find the attached file.

**Comment by balajikaliappan** [comment]
I building a app which should work on Linux . It is 64 bit Linux with
java1.6 version.

**Comment by saudet** [comment]
That sounds like an old version of Linux, so your problem is probably related to this issue:
https://github.com/bytedeco/javacpp-presets/issues/22
If rebuilding FFmpeg from scratch doesn't help, please let me know! Thanks
