### ISSUE TITLE
Parser error with static declarations

### ISSUE THREAD

**Issue by ashleyj** [bytedeco/javacpp#114]
Parser error occured on the following static method:

```
  static GlobalListType Module::*getSublistAccess(GlobalVariable*) {
    return &Module::GlobalList;
  }
```
ST

```
Caused by: org.bytedeco.javacpp.tools.ParserException: /Users/ash/src/javacpp-presets/llvm/cppbuild/macosx-x86_64/include/llvm/IR/Module.h:463: Could not parse declaration at '::'
	at org.bytedeco.javacpp.tools.Parser.declarations(Parser.java:2731)
	at org.bytedeco.javacpp.tools.Parser.group(Parser.java:2299)
	at org.bytedeco.javacpp.tools.Parser.declarations(Parser.java:2725)
	at org.bytedeco.javacpp.tools.Parser.namespace(Parser.java:2629)
	at org.bytedeco.javacpp.tools.Parser.declarations(Parser.java:2724)
	at org.bytedeco.javacpp.tools.Parser.parse(Parser.java:2804)
	at org.bytedeco.javacpp.tools.Parser.parse(Parser.java:2909)
	at org.bytedeco.javacpp.tools.Builder.parse(Builder.java:69)
	at org.bytedeco.javacpp.tools.Builder.build(Builder.java:652)
	at org.bytedeco.javacpp.tools.BuildMojo.execute(BuildMojo.java:235)
	
```

**Comment by saudet** [comment]
This is valid C++? Wow

**Comment by saudet** [comment]
I've fixed that in the latest commit. Let me know if you still have issues with that! Thanks for reporting.

**Comment by ashleyj** [comment]
All fixed, thanks
