### ISSUE TITLE
parse error subclass access

### ISSUE THREAD

**Issue by ashleyj** [bytedeco/javacpp#118]
Getting a parse error on the following block of code (llvm - GlobalValue.h)
Code:
```
  static const unsigned GlobalValueSubClassDataBits = 19;

private:
  // Give subclasses access to what otherwise would be wasted padding.
  // (19 + 3 + 2 + 1 + 2 + 5) == 32.
  unsigned SubClassData : GlobalValueSubClassDataBits;
```

ST:
```
Caused by: org.bytedeco.javacpp.tools.ParserException: /Users/ash/src/javacpp-presets/llvm/cppbuild/macosx-x86_64/include/llvm/IR/GlobalValue.h:92: Unexpected token 'GlobalValueSubClassDataBits'
	at org.bytedeco.javacpp.tools.Token.expect(Token.java:100)
	at org.bytedeco.javacpp.tools.Parser.declarator(Parser.java:917)
	at org.bytedeco.javacpp.tools.Parser.function(Parser.java:1553)
	at org.bytedeco.javacpp.tools.Parser.declarations(Parser.java:2763)
	at org.bytedeco.javacpp.tools.Parser.group(Parser.java:2336)
	at org.bytedeco.javacpp.tools.Parser.declarations(Parser.java:2762)
	at org.bytedeco.javacpp.tools.Parser.namespace(Parser.java:2666)
	at org.bytedeco.javacpp.tools.Parser.declarations(Parser.java:2761)
	at org.bytedeco.javacpp.tools.Parser.parse(Parser.java:2841)
	at org.bytedeco.javacpp.tools.Parser.parse(Parser.java:2946)
	at org.bytedeco.javacpp.tools.Builder.parse(Builder.java:69)
	
```

**Comment by saudet** [comment]
Fixed! Thanks for reporting as usual :)

**Comment by ashleyj** [comment]
Thanks again 👍
