### ISSUE TITLE
Server credentials with ID "sonatype-nexus-staging" not found!

### ISSUE THREAD

**Issue by jenniferwillow** [bytedeco/javacpp#126]
The following error occurred when running Maven on the supplied pom.xml file

INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 21.995 s
[INFO] Finished at: 2016-08-28T10:14:37-07:00
[INFO] Final Memory: 38M/584M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.6:deploy (default-deploy) on project javacpp: Execution default-deploy of goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.6:deploy failed: Server credentials with ID "sonatype-nexus-staging" not found! -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.6:deploy (default-deploy) on project javacpp: Execution default-deploy of goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.6:deploy failed: Server credentials with ID "sonatype-nexus-staging" not found!
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-deploy of goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.6:deploy failed: Server credentials with ID "sonatype-nexus-staging" not found!
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.lang.IllegalArgumentException: Server credentials with ID "sonatype-nexus-staging" not found!
	at org.sonatype.nexus.maven.staging.remote.RemoteNexus.<init>(RemoteNexus.java:81)
	at org.sonatype.nexus.maven.staging.deploy.strategy.AbstractStagingDeployStrategy.createRemoteNexus(AbstractStagingDeployStrategy.java:54)
	at org.sonatype.nexus.maven.staging.deploy.strategy.StagingDeployStrategy.deployPerModule(StagingDeployStrategy.java:70)
	at org.sonatype.nexus.maven.staging.deploy.DeployMojo.execute(DeployMojo.java:192)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more

**Comment by saudet** [comment]
Don't execute the "deploy" phase, do "install" instead:
https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html

**Comment by jenniferwillow** [comment]
Hi Samuel,
     Thanks for the help.  I rarely use Maven and I clearly used the incorrect phase.  Javacpp and javacv compiled with no issue.  However, when I went to install the javacpp-presets I ran into the following problem.  The opencv presets compiled correctly the system failed when compiling ffmpeg due to an unknown flag.  Here’s the output:

Sincerely,
Jennifer Milburn 

nasm -DUNIX64 -DPREFIX -f macho64 -I./codec/common/x86/   -o codec/common/x86/cpuid.o codec/common/x86/cpuid.asm
nasm -DUNIX64 -DPREFIX -f macho64 -I./codec/common/x86/   -o codec/common/x86/deblock.o codec/common/x86/deblock.asm
nasm -DUNIX64 -DPREFIX -f macho64 -I./codec/common/x86/   -o codec/common/x86/expand_picture.o codec/common/x86/expand_picture.asm
nasm -DUNIX64 -DPREFIX -f macho64 -I./codec/common/x86/   -o codec/common/x86/intra_pred_com.o codec/common/x86/intra_pred_com.asm
nasm: fatal: unrecognised output format `macho64' - use -hf for a list
type `nasm -h' for help
make: *** [codec/common/x86/cpuid.o] Error 1
make: *** Waiting for unfinished jobs....
nasm: fatal: unrecognised output format `macho64' - use -hf for a list
type `nasm -h' for help
make: *** [codec/common/x86/deblock.o] Error 1
nasm: fatal: unrecognised output format `macho64' - use -hf for a list
type `nasm -h' for help
make: *** [codec/common/x86/expand_picture.o] Error 1
nasm: fatal: unrecognised output format `macho64' - use -hf for a list
type `nasm -h' for help
make: *** [codec/common/x86/intra_pred_com.o] Error 1
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] JavaCPP Presets for FFmpeg ......................... FAILURE [03:09 min]
[INFO] JavaCPP Presets for FlyCapture ..................... SKIPPED
[INFO] JavaCPP Presets for libdc1394 ...................... SKIPPED
[INFO] JavaCPP Presets for libfreenect .................... SKIPPED
[INFO] JavaCPP Presets for videoInput ..................... SKIPPED
[INFO] JavaCPP Presets for ARToolKitPlus .................. SKIPPED
[INFO] JavaCPP Presets for Chilitags ...................... SKIPPED
[INFO] JavaCPP Presets for flandmark ...................... SKIPPED
[INFO] JavaCPP Presets for OpenBLAS ....................... SKIPPED
[INFO] JavaCPP Presets for FFTW ........................... SKIPPED
[INFO] JavaCPP Presets for GSL ............................ SKIPPED
[INFO] JavaCPP Presets for LLVM ........................... SKIPPED
[INFO] JavaCPP Presets for Leptonica ...................... SKIPPED
[INFO] JavaCPP Presets for Tesseract ...................... SKIPPED
[INFO] JavaCPP Presets for Caffe .......................... SKIPPED
[INFO] JavaCPP Presets for CUDA ........................... SKIPPED
[INFO] JavaCPP Presets for MXNet .......................... SKIPPED
[INFO] JavaCPP Presets for TensorFlow ..................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:10 min
[INFO] Finished at: 2016-08-29T08:08:29-07:00
[INFO] Final Memory: 17M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.4.0:exec (javacpp.cppbuild.install) on project ffmpeg: Command execution failed. Process exited with an error: 2 (Exit value: 2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by saudet** [comment]
For Mac OS X, please try to follow the instructions here:
https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments#mac-os-x-x86_64
