### ISSUE TITLE
JavaCpp BytePointer OutOfMemory error

### ISSUE THREAD

**Issue by tunahanbayindir** [bytedeco/javacpp#130]
Updated JavaCv and JavaCpp today, now it gives an OutOfMemoryError.
`
No implementation found for long org.bytedeco.javacpp.Pointer.physicalBytes() (tried Java_org_bytedeco_javacpp_Pointer_physicalBytes and Java_org_bytedeco_javacpp_Pointer_physicalBytes__)`

with this print trace and 

`java.lang.OutOfMemoryError: Cannot allocate 267850702 + 614403 bytes (> Pointer.maxBytes)
                                                                         at org.bytedeco.javacpp.Pointer.deallocator(Pointer.java:543)
                                                                         at org.bytedeco.javacpp.Pointer.init(Pointer.java:121)
                                                                         at org.bytedeco.javacpp.BytePointer.allocateArray(Native Method)
                                                                         at org.bytedeco.javacpp.BytePointer.<init>(BytePointer.java:82)
                                                                         at org.bytedeco.javacv.FFmpegFrameFilter.pushImage(FFmpegFrameFilter.java:265)
                                                                         at org.bytedeco.javacv.FFmpegFrameFilter.push(FFmpegFrameFilter.java:252)
                                                                         at org.bytedeco.javacv.FFmpegFrameFilter.push(FFmpegFrameFilter.java:248)`

this error code.
Need really urgent help. Best regards.

**Comment by saudet** [comment]
Increase that value, usually with the java -Xmx command line flag option.

**Comment by tunahanbayindir** [comment]
Don't know how to do. Any help, I am using Android Studio.

**Comment by saudet** [comment]
https://developer.android.com/guide/topics/manifest/application-element.html#largeHeap

**Comment by tunahanbayindir** [comment]
thanks a lot. largeHeap did the trick but it used about 400mbs when recording video with javacpp. Isn't it extremely high??

**Comment by saudet** [comment]
If you feel that's too high, please file a ticket about that upstream.

**Comment by amosyuen** [comment]
I'm also running into this error even while using largeHeap. It's fine with videos under 15s, but around 20s, I run into the error. The preview size was 1056 x 864.

Specifically this is happening when using it in my library https://github.com/amosyuen/FFmpegVideoRecorder on a Galaxy Samsung S5.
