### ISSUE TITLE
How to use librealsense presets binaries?

### ISSUE THREAD

**Issue by mattdibi** [bytedeco/javacpp#170]
Hi, 
I'm having troubles running your [librealsense example](https://github.com/bytedeco/javacpp-presets/tree/master/librealsense).
Here's what I did.
This is my folder structure:
```sh
.
├── javacpp-presets-bin
└──TestConnection.java
```
I then run:
```sh
$ javac -cp javacpp-presets-bin/javacpp.jar:javacpp-presets-bin/librealsense.jar TestConnection.java
$ java -jar javacpp-presets-bin/javacpp.jar TestConnection
Warning: Could not load platform properties for class TestConnection
$ java -cp javacpp-presets-bin/javacpp.jar:javacpp-presets-bin/librealsense.jar:. TestConnection
```
And I get this error:
```sh
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniRealSense in java.library.path
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
    at java.lang.Runtime.loadLibrary0(Runtime.java:870)
    at java.lang.System.loadLibrary(System.java:1122)
    at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:804)
    at org.bytedeco.javacpp.Loader.load(Loader.java:613)
    at org.bytedeco.javacpp.Loader.load(Loader.java:530)
    at org.bytedeco.javacpp.RealSense.<clinit>(RealSense.java:10)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at org.bytedeco.javacpp.Loader.load(Loader.java:585)
    at org.bytedeco.javacpp.Loader.load(Loader.java:530)
    at org.bytedeco.javacpp.RealSense$context.<clinit>(RealSense.java:1566)
    at TestConnection.main(TestConnection.java:8)
Caused by: java.lang.UnsatisfiedLinkError: no realsense in java.library.path
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
    at java.lang.Runtime.loadLibrary0(Runtime.java:870)
    at java.lang.System.loadLibrary(System.java:1122)
    at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:804)
    at org.bytedeco.javacpp.Loader.load(Loader.java:604)
    ... 8 more
```
Am I missing something? 
Any help is appreciated.

**Comment by saudet** [comment]
Please use the `librealsense-platform.jar` instead.

**Comment by mattdibi** [comment]
Yep... It worked! Thanks.
