### ISSUE TITLE
Raspberry Pi native shared library

### ISSUE THREAD

**Issue by AlexanderShniperson** [bytedeco/javacpp#191]
Hi, i exactly don't understand how do you use JavaCPP
i want to write Java library to handle Raspberry Pi camera module to take pictures
here is the simple C header:
[bcm_host.h](https://github.com/raspberrypi/firmware/blob/master/opt/vc/include/bcm_host.h)
and here is the shared library [libbcm_host.so](https://github.com/raspberrypi/firmware/blob/master/opt/vc/lib/libbcm_host.so)
on the target system library placed in directory `/opt/vc/lib`

i want to implement two methods
```
void bcm_host_init(void);
void bcm_host_deinit(void);
```
my question is:
- how my Java class LibBcmHost should looks like?
- what steps should i do to compile and run this two methods?

thanks

**Comment by AlexanderShniperson** [comment]
it is how i am doing it
```
import org.bytedeco.javacpp.Loader;
import org.bytedeco.javacpp.Pointer;
import org.bytedeco.javacpp.annotation.Platform;
import org.bytedeco.javacpp.annotation.Properties;

@Properties(
@Platform(
        cinclude = "bcm_host.h",
        link = "bcm_host",
        library = "libbcm_host.so",
        includepath = {"/opt/vc/include", "/opt/vc/lib"},
        linkpath = "/opt/vc/lib")
)
public class LibBcmHost {
    static {
        Loader.load();
    }

    public native void bcm_host_init();

    public native void bcm_host_deinit();
}
```
and when i try to run my program
```
public class MainApp {
    public static void main(String[] args) {
        try {
            LibBcmHost libBcm = new LibBcmHost();
            libBcm.bcm_host_init();
            Thread.sleep(1000);
            libBcm.bcm_host_deinit();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}
```
i got 
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no libbcm_host.so in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:963)
	at org.bytedeco.javacpp.Loader.load(Loader.java:764)
	at org.bytedeco.javacpp.Loader.load(Loader.java:671)
	at org.raspberry.camera.bindings.LibBcmHost.<clinit>(LibBcmHost.java:18)
	at org.raspberry.camera.MainApp.main(MainApp.java:8)
```

**Comment by saudet** [comment]
Looks ok, but did you run the Builder as shown in the README.md file by
executing `java -jar javacpp.jar LibBcmHost`, for example?

2017/07/06 21:08 "Alexander Shniperson" <notifications@github.com>:

it is how i am doing it

import org.bytedeco.javacpp.Loader;
import org.bytedeco.javacpp.Pointer;
import org.bytedeco.javacpp.annotation.Platform;
import org.bytedeco.javacpp.annotation.Properties;

@Properties(
@Platform(
        cinclude = "bcm_host.h",
        link = "bcm_host",
        library = "libbcm_host.so",
        includepath = {"/opt/vc/include", "/opt/vc/lib"},
        linkpath = "/opt/vc/lib")
)
public class LibBcmHost {
    static {
        Loader.load();
    }

    public native void bcm_host_init();

    public native void bcm_host_deinit();
}

and when i try to run my program

public class MainApp {
    public static void main(String[] args) {
        try {
            LibBcmHost libBcm = new LibBcmHost();
            libBcm.bcm_host_init();
            Thread.sleep(1000);
            libBcm.bcm_host_deinit();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}

i got

Exception in thread "main" java.lang.UnsatisfiedLinkError: no
libbcm_host.so in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:963)
	at org.bytedeco.javacpp.Loader.load(Loader.java:764)
	at org.bytedeco.javacpp.Loader.load(Loader.java:671)
	at org.raspberry.camera.bindings.LibBcmHost.<clinit>(LibBcmHost.java:18)
	at org.raspberry.camera.MainApp.main(MainApp.java:8)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/bytedeco/javacpp/issues/191#issuecomment-313377634>,
or mute
the thread

**Comment by AlexanderShniperson** [comment]
no i did'nt
1) now a did this `javac -cp $JAVACPPHOME/javacpp.jar ./src/main/java/org/raspberry/camera/bindings/LibBcmHost.java`
2) and then `java -jar $JAVACPPHOME/javacpp.jar ./src/main/java/org/raspberry/camera/bindings/LibBcmHost`
and after second stage i have 
```
Exception in thread "main" java.lang.ClassNotFoundException: //src/main/java/org/raspberry/camera/bindings/LibBcmHost
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.tools.ClassScanner.addClass(ClassScanner.java:61)
	at org.bytedeco.javacpp.tools.ClassScanner.addClassOrPackage(ClassScanner.java:129)
	at org.bytedeco.javacpp.tools.Builder.classesOrPackages(Builder.java:616)
	at org.bytedeco.javacpp.tools.Builder.main(Builder.java:807)
```

**Comment by saudet** [comment]
We need to use the *class name*, not the filename.

2017/07/07 0:04 "Alexander Shniperson" <notifications@github.com>:

**Comment by saudet** [comment]
Please run exactly the same commands as the examples given in the README.md file and it will work.

**Comment by AlexanderShniperson** [comment]
@saudet 
yes thank you it works
