### ISSUE TITLE
Expected in: flat namespace

### ISSUE THREAD

**Issue by louxiu** [bytedeco/javacpp#216]
I create and install the preset successfully, but when I use it, I got the error bellow.
The lib(live_transport) is built with google protobuf headers and lib which I compiled from source. 
Please tell me if any more infos is needed?  Thanks in advance.

``` 
objc[9485]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/bin/java (0x1078084c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x10888b4e0). One of the two will be used. Which one is undefined.
Exception in thread "main" java.lang.UnsatisfiedLinkError: no live_transport in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:976)
	at org.bytedeco.javacpp.Loader.load(Loader.java:777)
	at org.bytedeco.javacpp.Loader.load(Loader.java:684)
	at org.bytedeco.javacpp.liblivetransport.<clinit>(liblivetransport.java:10)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:739)
	at org.bytedeco.javacpp.Loader.load(Loader.java:684)
	at org.bytedeco.javacpp.liblivetransport$LiveClientConfig.<clinit>(liblivetransport.java:92)
	at Cmd2.main(Cmd2.java:15)
Caused by: java.lang.UnsatisfiedLinkError: /Users/louxiu/projects/javacpp-presets/liblivetransport/target/classes/org/bytedeco/javacpp/macosx-x86_64/liblive_transport.dylib: dlopen(/Users/louxiu/projects/javacpp-presets/liblivetransport/target/classes/org/bytedeco/javacpp/macosx-x86_64/liblive_transport.dylib, 1): Symbol not found: __ZNK6google9protobuf211MessageLite25InitializationErrorStringEv
  Referenced from: /Users/louxiu/projects/javacpp-presets/liblivetransport/target/classes/org/bytedeco/javacpp/macosx-x86_64/liblive_transport.dylib
  Expected in: flat namespace
 in /Users/louxiu/projects/javacpp-presets/liblivetransport/target/classes/org/bytedeco/javacpp/macosx-x86_64/liblive_transport.dylib
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:956)
	... 9 more
```

**Comment by saudet** [comment]
That looks like the your library wasn't linked with an `@rpath` in it. Check with `otool -L`, and in the worst case, use `install_name_tool` like this:
> install_name_tool -add_rpath @loader_path/. -id @rpath/libmxnet.so ../lib/libmxnet.so

https://github.com/bytedeco/javacpp-presets/blob/master/mxnet/cppbuild.sh#L94

**Comment by louxiu** [comment]
Come to get help again. :-( I tried but without luck. The lib has no dependence on protobuf(As linked it with static).  
```
otool -L /Users/louxiu/projects/javacpp-presets/libliveclient/target/classes/org/bytedeco/javacpp/macosx-x86_64/liblive_client.dylib
/Users/louxiu/projects/javacpp-presets/libliveclient/target/classes/org/bytedeco/javacpp/macosx-x86_64/liblive_client.dylib:
        liblive_client.dylib (compatibility version 0.0.0, current version 0.0.0)
        /System/Library/Frameworks/JavaVM.framework/Versions/A/JavaVM (compatibility version 1.0.0, current version 1.0.0)
        /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
```
And this is my main function.
``` java
    public static void main(String[] args) {
        System.setProperty("java.library.path",
                System.getProperty("java.library.path") + File.pathSeparator
                        + "/Users/louxiu/projects/javacpp-presets/libliveclient/target/classes/org/bytedeco/javacpp/macosx-x86_64");
        libliveclient.LiveClientConfig config = new libliveclient.LiveClientConfig();

        libliveclient.LiveClient liveClient = libliveclient.LiveClient.Create(config);

    }
```
PS: I renamed livetransport with libliveclient.

**Comment by saudet** [comment]
So it's not using @rpath. Fix that and a whole lot of things should start going right.

**Comment by louxiu** [comment]
Sorry if this is a stupid question. As I don't have much faith with linking . I am a bit confused with your comment. 

At this comment, `libliveclient.dylib` is the dynamic lib that javacpp finally generated. `libliveclient.dylib` = `liblivetransport.a` static linked with JNI. `liblivetransport.a` includes a static linked `libprotobuf.a`.

 Do you mean I should make `liblivetransport.a` dynamic(to `liblivetransport.so` or `liblivetransport.dylib`) and use @rpath link `liblivetransport.dylib` and JNI to make `libliveclient.dylib`?

Thanks for your patience.

**Comment by saudet** [comment]
You have only one dylib? Then yes we don't need to worry about @rpath. In
any case, it doesn't look related to JavaCPP. Does it happen outside Java?

**Comment by louxiu** [comment]
@saudet :smiley: You are right. This is not related javaCPP. `liblivetransport.a` static linked with `libprotobuf.a` but not include it. Solve this problem by link with `libprotobuf.a` when built `libliveclient.dylib`. Thanks
