### ISSUE TITLE
java.lang.UnsatisfiedLinkError when using eclipse

### ISSUE THREAD

**Issue by jues** [bytedeco/javacpp#222]
Hi, I've followed the first example in Readme.md and generated the lib successfully. Then I created an eclipse project including everything in it. And created a new Nativetest.java contains following code:

```
package main;

import main.NativeLibrary.NativeClass;

public class Nativetest {
    public static void main(String[] args) {
        NativeClass l = new NativeClass();
        l.set_property("Hello World!");
        System.out.println(l.property());
    }
}
```

I've set the jni path, included the jar, but there is still an error:     

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: main.NativeLibrary$NativeClass.allocate()V
	at main.NativeLibrary$NativeClass.allocate(Native Method)
	at main.NativeLibrary$NativeClass.<init>(NativeLibrary.java:10)
	at main.NativeLibrary.main(NativeLibrary.java:23)
```

What did I missed?

**Comment by jues** [comment]
When I put NativeLibrary.java in a package, `java -jar javacpp.jar main.NativeLibrary`will generate a `-lNativeLibrary` parameter which is not found, how to solve that?

**Comment by saudet** [comment]
You forget to call Loader.load(), System.load(), or System.loadLibrary().

**Comment by jues** [comment]
But I'm using the NativeLibrary.java from example?
```

package main;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

@Platform(include="NativeLibrary.h")
@Namespace("NativeLibrary")
public class NativeLibrary {
    public static class NativeClass extends Pointer {
        static { Loader.load(); }
        public NativeClass() { allocate(); }
        private native void allocate();

        // to call the getter and setter functions 
        public native @StdString String get_property(); public native void set_property(String property);

        // to access the member variable directly
        public native @StdString String property();     public native void property(String property);
    }

    public static void main(String[] args) {
        // Pointer objects allocated in Java get deallocated once they become unreachable,
        // but C++ destructors can still be called in a timely fashion with Pointer.deallocate()
        NativeClass l = new NativeClass();
        l.set_property("Hello World!");
        System.out.println(l.property());
    }
}
```

**Comment by saudet** [comment]
So you didn't run the commands given at https://github.com/bytedeco/javacpp#accessing-native-apis ?

**Comment by jues** [comment]
I have run it, inported the generated `libjniNativeLibrary.dylib` by setting Native Library location of the project

**Comment by jues** [comment]
Oh, I solved the problem,
at step2, `java -jar javacpp.jar main.NativeLibrary`generates `clang++ -I/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/include/darwin /Users/ooyama/Downloads/javacpp/main/jniNativeLibrary.cpp -march=x86-64 -m64 -O3 -Wl,-rpath,@loader_path/. -Wall -fPIC -dynamiclib -undefined dynamic_lookup -o libjniNativeLibrary.dylib -lNativeLibrary -framework JavaVM ` which will cause a` ld: library not found for -lNativeLibrary` error.    
Just remove the `-lNativeLibrary ` by hand, then copy the generated libjniNativeLibrary.dylib to the Native Library location of the project will do.
Thank you very much!!!!

**Comment by saudet** [comment]
This isn't happening with 1.3.4-SNAPSHOT:
```
Compiling /Users/admin/macosx-x86_64/libjniNativeLibrary.dylib
clang++ -I/Library/Java/JavaVirtualMachines/jdk1.8.0_141.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/jdk1.8.0_141.jdk/Contents/Home/include/darwin /Users/admin/jniNativeLibrary.cpp /Users/admin/jnijavacpp.cpp -march=x86-64 -m64 -O3 -Wl,-rpath,@loader_path/. -Wall -fPIC -dynamiclib -undefined dynamic_lookup -o libjniNativeLibrary.dylib -framework JavaVM 
```
So, whatever the problem was, it's already been fixed.

**Comment by jues** [comment]
@saudet  I added a line `package main;`at the top of NativeLibrary, and using     
`javac -cp javacpp.jar main/NativeLibrary.java`
then    
`java -jar javacpp.jar main.NativeLibrary`     
it's ok without package

**Comment by jues** [comment]
```
$ javac -cp javacpp-1.3.4-20171222.122315-33.jar test/CMU002Library.java
$ java -jar javacpp-1.3.4-20171222.122315-33.jar test.CMU002Library
Generating /Users/admin/javacpp/test/jnijavacpp.cpp
Generating /Users/admin/javacpp/test/jniCMU002Library.cpp
Compiling /Users/admin/javacpp/test/macosx-x86_64/libjniCMU002Library.dylib
clang++ -I/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/include/darwin /Users/admin/javacpp/test/jniCMU002Library.cpp /Users/admin/javacpp/test/jnijavacpp.cpp -march=x86-64 -m64 -O3 -Wl,-rpath,@loader_path/. -Wall -fPIC -dynamiclib -undefined dynamic_lookup -o libjniCMU002Library.dylib -lCMU002Library -framework JavaVM 
In file included from /Users/ooyama/Downloads/javacpp/test/jniCMU002Library.cpp:88:
/Users/admin/javacpp/test/CMU002Library.h:205:25: warning: equality comparison with
      extraneous parentheses [-Wparentheses-equality]
                if ((coronary_disease == 1))
                     ~~~~~~~~~~~~~~~~~^~~~
/Users/admin/javacpp/test/CMU002Library.h:205:25: note: remove extraneous
      parentheses around the comparison to silence this warning
                if ((coronary_disease == 1))
                    ~                 ^   ~
/Users/admin/javacpp/test/CMU002Library.h:205:25: note: use '=' to turn this
      equality comparison into an assignment
                if ((coronary_disease == 1))
                                      ^~
                                      =
1 warning generated.
ld: library not found for -lCMU002Library
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Exception in thread "main" java.lang.RuntimeException: Process exited with an error: 1
	at org.bytedeco.javacpp.tools.Builder.generateAndCompile(Builder.java:487)
	at org.bytedeco.javacpp.tools.Builder.build(Builder.java:868)
	at org.bytedeco.javacpp.tools.Builder.main(Builder.java:1050)
```

**Comment by saudet** [comment]
It still doesn't happen here. Like I said, please try a more recent version of JavaCPP.
