### ISSUE TITLE
java.lang.NoClassDefFoundError: org/bytedeco/javacpp/opencv_core$RotatedRect

### ISSUE THREAD

**Issue by Menneken** [bytedeco/javacpp#234]
Hi,
I plan to use JavaCV together with Joheras 'IJ-OpenCV' to implement OpenCV functionality in the ImageJ/Fiji app.
I think my installation routine using Maven/Eclipse was fine, all .jars (javacpp-1.4, javacv-1.4, javacv-platform-1.4, opencv-platform-3.4.0-1.4 etc.) were copied to the directory I wanted them to be, but when opening ImageJ/Fiji, I get the following error:

`java.lang.NoClassDefFoundError: org/bytedeco/javacpp/opencv_core$RotatedRect
	at ijopencv.ij.EllipseRoiRotatedRectConverter.getOutputType(EllipseRoiRotatedRectConverter.java:44)
	at org.scijava.convert.AbstractConvertService.getCompatibleOutputClasses(AbstractConvertService.java:152)
	at net.imagej.display.process.SingleInputPreprocessor.getSingleInput(SingleInputPreprocessor.java:102)
	at net.imagej.display.process.SingleInputPreprocessor.process(SingleInputPreprocessor.java:81)
	at org.scijava.module.ModuleRunner.preProcess(ModuleRunner.java:104)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:156)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:126)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:65)
	at org.scijava.thread.DefaultThreadService$2.call(DefaultThreadService.java:191)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.bytedeco.javacpp.opencv_core$RotatedRect
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 13 more
`
Could you plese help me out here?

**Comment by saudet** [comment]
You'll need to add the JAR files for your platform as well, the ones with
"linux", "macosx", "windows" in their names.
