### ISSUE TITLE
Intellij Idea issue

### ISSUE THREAD

**Issue by SergeyPod** [bytedeco/javacpp#28]
Dear developers,
Thanks for this very useful library. 

I am trying to play with simple classes in intellij idea and it seems I'm missing something. My c++ class header:

```c
#ifndef IMMANAGER_H
#define	IMMANAGER_H
class imManager 
{
    imManager();
};
#endif	/* IMMANAGER_H */
```
I've build correspondent library libCppDynamicLibrary.dylib and try to use in Java in the next way:

```java
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;
@Platform(include = "/path/CppDynamicLibrary/imManager.h", link = "CppDynamicLibrary")
    public class imManager extends Pointer {
        static { Loader.load(); }
        public imManager() { allocate(); }
        private native void allocate();
}
```

After compiling and running that with Intellij Idea I'm getting:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniimManager in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1119)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:550)
	at org.bytedeco.javacpp.Loader.load(Loader.java:415)
	at org.bytedeco.javacpp.Loader.load(Loader.java:358)
	at imManager.<clinit>(imManager.java:26)
	at entryClass.main(entryClass.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

Process finished with exit code 1
```

the C++ library (libCppDynamicLibrary.dylib) is in 
-Djava.library.path="/path/GNU_macpors-MacOSX" which added to "VM options" of "Edit configurations..." dialog

Could you help me to resolve that issue?
Thanks a lot.

<b>UPDATE:</b>
I have renamed library to the jniimManager but now getting
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: imManager.allocate()V
```

With best regards,
Sergey

**Comment by saudet** [comment]
How are you compiling the jniimManager library?

**Comment by SergeyPod** [comment]
AFAIK Idea does not use any command line tool, it coplile using API. So I just run "Make project".
Thanks

**Comment by saudet** [comment]
So, you could use the Maven Mojo to build it then...

**Comment by SergeyPod** [comment]
Thank you very much!

**Comment by saudet** [comment]
Well, at first it's probably easier to use the command line tool as shown in the example of the README.md file. Just run those commands before executing anything in the IDE. That will work for now and we can think of integrating that better with your project files at some later point in time!

**Comment by nhattanmai** [comment]
I have same error, and how to use Maven Mojo in Intellij Idea?

**Comment by saudet** [comment]
Try to do something similar to the presets: https://github.com/bytedeco/javacpp-presets/wiki/Create-New-Presets
I agree I have to update the guide for Maven though...
