### ISSUE TITLE
javacpp DoublePointer OOM

### ISSUE THREAD

**Issue by cuckootan** [bytedeco/javacpp#282]
Hi, I encountered some errors recently, but I can't know why. Can you help me check that please? Thanks in advance!

The errors are as follows:

```
java.lang.OutOfMemoryError: Cannot allocate new DoublePointer(301): totalBytes = 3977, physicalBytes = 32813M
	at org.bytedeco.javacpp.DoublePointer.<init>(DoublePointer.java:76) ~[javacpp-1.4.2.jar:1.4.2]
	at org.bytedeco.javacpp.DoublePointer.<init>(DoublePointer.java:41) ~[javacpp-1.4.2.jar:1.4.2]
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.<init>(BaseDataBuffer.java:336) ~[nd4j-buffer-1.0.0-beta2.jar:?]
	at org.nd4j.linalg.api.buffer.DoubleBuffer.<init>(DoubleBuffer.java:116) ~[nd4j-buffer-1.0.0-beta2.jar:?]
	at org.nd4j.linalg.api.buffer.factory.DefaultDataBufferFactory.createDouble(DefaultDataBufferFactory.java:461) ~[nd4j-buffer-1.0.0-beta2.jar:?]
	at org.nd4j.linalg.api.buffer.factory.DefaultDataBufferFactory.createDouble(DefaultDataBufferFactory.java:351) ~[nd4j-buffer-1.0.0-beta2.jar:?]
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1555) ~[nd4j-api-1.0.0-beta2.jar:1.0.0-beta2]
	at org.nd4j.linalg.api.ndarray.BaseNDArray.internalCreateBuffer(BaseNDArray.java:602) ~[nd4j-api-1.0.0-beta2.jar:1.0.0-beta2]
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:862) ~[nd4j-api-1.0.0-beta2.jar:1.0.0-beta2]
	at org.nd4j.linalg.cpu.nativecpu.NDArray.<init>(NDArray.java:353) ~[nd4j-native-1.0.0-beta2.jar:?]
	at org.nd4j.linalg.cpu.nativecpu.CpuNDArrayFactory.create(CpuNDArrayFactory.java:333) ~[nd4j-native-1.0.0-beta2.jar:?]
	at org.nd4j.linalg.factory.BaseNDArrayFactory.create(BaseNDArrayFactory.java:1119) ~[nd4j-api-1.0.0-beta2.jar:1.0.0-beta2]
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3461) ~[nd4j-api-1.0.0-beta2.jar:1.0.0-beta2]
```

```
java.lang.OutOfMemoryError: Physical memory usage is too high: physicalBytes (32813M) > maxPhysicalBytes (32768M)
	at org.bytedeco.javacpp.Pointer.deallocator(Pointer.java:588) ~[javacpp-1.4.2.jar:1.4.2]
	at org.bytedeco.javacpp.Pointer.init(Pointer.java:124) ~[javacpp-1.4.2.jar:1.4.2]
	at org.bytedeco.javacpp.DoublePointer.allocateArray(Native Method) ~[javacpp-1.4.2.jar:1.4.2]
	at org.bytedeco.javacpp.DoublePointer.<init>(DoublePointer.java:68) ~[javacpp-1.4.2.jar:1.4.2]
	at org.bytedeco.javacpp.DoublePointer.<init>(DoublePointer.java:41) ~[javacpp-1.4.2.jar:1.4.2]
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.<init>(BaseDataBuffer.java:336) ~[nd4j-buffer-1.0.0-beta2.jar:?]
	at org.nd4j.linalg.api.buffer.DoubleBuffer.<init>(DoubleBuffer.java:116) ~[nd4j-buffer-1.0.0-beta2.jar:?]
	at org.nd4j.linalg.api.buffer.factory.DefaultDataBufferFactory.createDouble(DefaultDataBufferFactory.java:461) ~[nd4j-buffer-1.0.0-beta2.jar:?]
	at org.nd4j.linalg.api.buffer.factory.DefaultDataBufferFactory.createDouble(DefaultDataBufferFactory.java:351) ~[nd4j-buffer-1.0.0-beta2.jar:?]
	at org.nd4j.linalg.factory.Nd4j.createBuffer(Nd4j.java:1555) ~[nd4j-api-1.0.0-beta2.jar:1.0.0-beta2]
	at org.nd4j.linalg.api.ndarray.BaseNDArray.internalCreateBuffer(BaseNDArray.java:602) ~[nd4j-api-1.0.0-beta2.jar:1.0.0-beta2]
	at org.nd4j.linalg.api.ndarray.BaseNDArray.<init>(BaseNDArray.java:862) ~[nd4j-api-1.0.0-beta2.jar:1.0.0-beta2]
	at org.nd4j.linalg.cpu.nativecpu.NDArray.<init>(NDArray.java:353) ~[nd4j-native-1.0.0-beta2.jar:?]
	at org.nd4j.linalg.cpu.nativecpu.CpuNDArrayFactory.create(CpuNDArrayFactory.java:333) ~[nd4j-native-1.0.0-beta2.jar:?]
	at org.nd4j.linalg.factory.BaseNDArrayFactory.create(BaseNDArrayFactory.java:1119) ~[nd4j-api-1.0.0-beta2.jar:1.0.0-beta2]
	at org.nd4j.linalg.factory.Nd4j.create(Nd4j.java:3461) ~[nd4j-api-1.0.0-beta2.jar:1.0.0-beta2]
```

OS: Linux
total physical memory: 251G
jvm stack memory: 16G
off heap memory(-XX:MaxDirectMemorySize=2048m): 2G

**Comment by cuckootan** [comment]
oh, I forgot something. The version of javacpp is 1.4.2~

**Comment by cuckootan** [comment]
> You'll need to increase available memory. There are some explainings here:
> https://deeplearning4j.org/docs/latest/deeplearning4j-config-memory

You mean set the -Dorg.bytedeco.javacpp.maxbytes?

Well, I have some extra problems:

1. What's the default value of "org.bytedeco.javacpp.maxbytes"?
2. Is the option "-XX:MaxDirectMemorySize=2048m" irrelevant to memory management in javacpp/nd4j?
3. What's the relation between "org.bytedeco.javacpp.maxbytes" and "totalBytes", "physicalBytes" in error message above?

**Comment by saudet** [comment]
Additional precisions here: http://bytedeco.org/javacpp/apidocs/org/bytedeco/javacpp/Pointer.html

MaxDirectMemorySize isn't used. It's not available on some JVMs like Android, and although we can peek at its value from "sun.nio.MaxDirectMemorySize" and use it as default for "maxBytes", it's actually a separate pool of memory, so it doesn't make much sense.

**Comment by cuckootan** [comment]
> Additional precisions here: http://bytedeco.org/javacpp/apidocs/org/bytedeco/javacpp/Pointer.html
> 
> MaxDirectMemorySize isn't used. It's not available on some JVMs like Android, and although we can peek at its value from "sun.nio.MaxDirectMemorySize" and use it as default for "maxBytes", it's actually a separate pool of memory, so it doesn't make much sense.

According to document, the value of "org.bytedeco.javacpp.maxbytes" defaults to 16G, because jvm stack memory is 16G. Wow, the value is so large but isn't still enough. It seems not to be a normal case.

**Comment by saudet** [comment]
You're hitting the maxPhysicalBytes limit, not maxBytes, something else is
leaking in your process.

**Comment by saudet** [comment]
Please upgrade to 1.0.0-beta3, a lot has been fixed.

**Comment by cuckootan** [comment]
> Please upgrade to 1.0.0-beta3, a lot has been fixed.

Ok, I'll try it. Thanks for your patience.
