### ISSUE TITLE
fatal error: 'exception' file not found

### ISSUE THREAD

**Issue by arden** [bytedeco/javacpp#286]
When I compile for Android platform on macos.

```
#!/bin/bash

ANDROID_HOME="/Users/arden/Library/Android/sdk"
ANDROID_NDK_HOME="/Users/arden/soft/android-ndk-r18b"
ANDROID_NDK_COMPILER="$ANDROID_NDK_HOME/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-g++"

javac -cp ../../../lib/javacpp.jar dog/tale/pitaya/PitayaConfig.java
java -jar ../../../lib/javacpp.jar dog.tale.pitaya.PitayaConfig -properties android-arm -Dplatform.root=$ANDROID_NDK_HOME -Dplatform.compiler=$ANDROID_NDK_COMPILER
javac -cp .:../../../lib/javacpp.jar dog/tale/pitaya/Pitaya.java
java -jar ../../../lib/javacpp.jar dog.tale.pitaya.Pitaya -properties android-arm -Dplatform.root=$ANDROID_NDK_HOME -Dplatform.compiler=$ANDROID_NDK_COMPILER
rm -rf dog/tale/pitaya/*.class
```

some errors below:

```
ardendeiMac:java arden$ ./build.sh 
Targeting dog/tale/pitaya/Pitaya.java
Parsing /Users/arden/data/repository/tale/PitayaClientJava/src/main/cpp/include/pitaya_version.h
Parsing /Users/arden/data/repository/tale/PitayaClientJava/src/main/cpp/include/pitaya.h
注: dog/tale/pitaya/Pitaya.java使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
Generating /Users/arden/data/repository/tale/PitayaClientJava/src/main/java/jnijavacpp.cpp
Generating /Users/arden/data/repository/tale/PitayaClientJava/src/main/java/dog/tale/pitaya/jniPitaya.cpp
Compiling /Users/arden/data/repository/tale/PitayaClientJava/src/main/java/lib/armeabi-v7a/libjniPitaya.so
/Users/arden/soft/android-ndk-r18b/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-g++ -I/Users/arden/soft/android-ndk-r18b/sysroot/usr/include/ -I/Users/arden/soft/android-ndk-r18b/sysroot/usr/include/arm-linux-androideabi/ -I/Users/arden/data/repository/tale/PitayaClientJava/src/main/cpp/include/ -I/Users/arden/data/source/go/game/libpitaya/src/ /Users/arden/data/repository/tale/PitayaClientJava/src/main/java/dog/tale/pitaya/jniPitaya.cpp /Users/arden/data/repository/tale/PitayaClientJava/src/main/java/jnijavacpp.cpp -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -funswitch-loops -finline-limit=300 -O3 -s -Wl,-rpath,lib/ -D__ANDROID_API__=14 -DANDROID -ffunction-sections -funwind-tables -fstack-protector -Wall -Wno-attributes -nodefaultlibs -fPIC -shared -Wl,--no-undefined -z text -o libjniPitaya.so -Wl,-soname,libjniPitaya.so -L/Users/arden/data/source/go/game/libpitaya/deps/ -llog -lgnustl_static -lgcc -ldl -lm -lc 
clang++: warning: optimization flag '-funswitch-loops' is not supported [-Wignored-optimization-argument]
clang++: warning: optimization flag '-finline-limit=300' is not supported [-Wignored-optimization-argument]
clang++: warning: optimization flag '-funswitch-loops' is not supported [-Wignored-optimization-argument]
clang++: warning: optimization flag '-finline-limit=300' is not supported [-Wignored-optimization-argument]
/Users/arden/data/repository/tale/PitayaClientJava/src/main/java/dog/tale/pitaya/jniPitaya.cpp:73:10: fatal error: 'exception' file not found
#include <exception>
         ^~~~~~~~~~~
1 error generated.
/Users/arden/data/repository/tale/PitayaClientJava/src/main/java/jnijavacpp.cpp:73:10: fatal error: 'exception' file not found
#include <exception>
         ^~~~~~~~~~~
1 error generated.
Exception in thread "main" java.lang.RuntimeException: Process exited with an error: 1
	at org.bytedeco.javacpp.tools.Builder.generateAndCompile(Builder.java:594)
	at org.bytedeco.javacpp.tools.Builder.build(Builder.java:1002)
	at org.bytedeco.javacpp.tools.Builder.main(Builder.java:1223)
```

**Comment by saudet** [comment]
Please try again with NDK r18.

**Comment by saudet** [comment]
With NDK r18, you'll need to use Clang with the android-xxx-clang.properties. On the command line that is "-properties android-xxx-clang".

**Comment by arden** [comment]
How do I specify custom android-xxx-clang.properties on the command line.

**Comment by saudet** [comment]
Instead of `-properties android-arm`, for example, use `-properties android-arm-clang`.

**Comment by arden** [comment]
`java -jar ../../../lib/javacpp.jar dog.tale.pitaya.Pitaya -properties android-arm-clang -Dplatform.root=$ANDROID_NDK_HOME -Dplatform.compiler=$ANDROID_NDK_COMPILER`

but can't find the methods defined in my c header files.

**Comment by saudet** [comment]
You'll need to add their locations to the "includepath". For some instructions, please refer to https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes.

**Comment by arden** [comment]
This is my PitayaConfig.java

```
package dog.tale.pitaya;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;
import org.bytedeco.javacpp.tools.*;

@Properties(
    target="dog.tale.pitaya.Pitaya",
    value = {
            @Platform(
                    value={""},
                    includepath = {"/Users/arden/data/repository/tale/PitayaClientJava/src/main/cpp/include/", "/Users/arden/data/source/go/game/libpitaya/src/"},
                    preloadpath = {"/Users/arden/data/source/go/game/libpitaya/deps/"},
                    linkpath = {"/Users/arden/data/source/go/game/libpitaya/deps/"},
                    cinclude = {"pitaya_version.h","pitaya.h"},
                    include = {},
                    library = "jniPitaya"
            )
    }

)
public class PitayaConfig implements InfoMapper {
    public void map(InfoMap infoMap) {
        //infoMap.put(new Info("std::string").annotations("@StdString").valueTypes("BytePointer", "String").pointerTypes("@Cast({\"char*\", \"std::string*\"}) BytePointer"));
        infoMap.put(new Info("PC_CLIENT_CONFIG_DEFAULT", "PC_EXPORT", "PC_VERSION_STR", "pc_lib_version_str()").cppTypes().annotations());
    }
}
```
i have added the c header files path to includepath already. and also added it to command includepath.

```
#!/bin/bash

ANDROID_HOME="/Users/arden/Library/Android/sdk"
ANDROID_NDK_HOME="/Users/arden/Library/Android/sdk/ndk-bundle"
ANDROID_NDK_COMPILER="$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++"
PITAYA_CPP_INCLUDEPATH="/Users/arden/data/repository/tale/PitayaClientJava/src/main/cpp/include"
PITAYA_CPP_SOURCE_INCLUDEPATH="/Users/arden/data/source/go/game/libpitaya/src"
CPP_INCLUDEPATH_HOME="$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include"
CPP_INCLUDEPATH="$PITAYA_CPP_INCLUDEPATH:$PITAYA_CPP_SOURCE_INCLUDEPATH:$ANDROID_NDK_HOME/sources/android/support/include:$ANDROID_NDK_HOME/sysroot/usr/include:$ANDROID_NDK_HOME/arm-linux-androideabi";

#javac -cp ../../../lib/javacpp.jar dog/tale/pitaya/PitayaConfig.java
#java -jar ../../../lib/javacpp.jar dog.tale.pitaya.PitayaConfig
#javac -cp .:../../../lib/javacpp.jar dog/tale/pitaya/Pitaya.java
#java -jar ../../../lib/javacpp.jar dog.tale.pitaya.Pitaya
##java -jar ../../../lib/javacpp.jar -nocompile dog.tale.pitaya.Pitaya
#rm -rf dog/tale/pitaya/*.class


javac -cp ../../../lib/javacpp.jar dog/tale/pitaya/PitayaConfig.java
java -jar ../../../lib/javacpp.jar dog.tale.pitaya.PitayaConfig -properties android-arm-clang -Dplatform.root=$ANDROID_NDK_HOME -Dplatform.compiler=$ANDROID_NDK_COMPILER -Dplatform.includepath=$CPP_INCLUDEPATH
javac -cp .:../../../lib/javacpp.jar dog/tale/pitaya/Pitaya.java
java -jar ../../../lib/javacpp.jar dog.tale.pitaya.Pitaya -properties android-arm-clang -Dplatform.root=$ANDROID_NDK_HOME -Dplatform.compiler=$ANDROID_NDK_COMPILER -Dplatform.includepath=$CPP_INCLUDEPATH
rm -rf dog/tale/pitaya/*.class
```
when i'm added my c header files to platform.includepath on command. 

```
/Users/arden/data/repository/tale/PitayaClientJava/src/main/java/dog/tale/pitaya/jniPitaya.cpp:73:10: fatal error: 'exception' file not found
#include <exception>
         ^~~~~~~~~~~
1 error generated.
/Users/arden/data/repository/tale/PitayaClientJava/src/main/java/jnijavacpp.cpp:73:10: fatal error: 'exception' file not found
#include <exception>
```

when i'm added NDK's "$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include" to platform.includepath on command also.

```
In file included from /Users/arden/Library/Android/sdk/ndk-bundle/sysroot/usr/include/sys/types.h:36:
/Users/arden/Library/Android/sdk/ndk-bundle/sysroot/usr/include/linux/types.h:21:10: fatal error: 'asm/types.h' file not found
#include <asm/types.h>
         ^~~~~~~~~~~~~
1 error generated.
In file included from /Users/arden/data/repository/tale/PitayaClientJava/src/main/java/jnijavacpp.cpp:30:
In file included from /Users/arden/Library/Android/sdk/ndk-bundle/sysroot/usr/include/pthread.h:33:
In file included from /Users/arden/Library/Android/sdk/ndk-bundle/sysroot/usr/include/bits/pthread_types.h:33:
In file included from /Users/arden/Library/Android/sdk/ndk-bundle/sysroot/usr/include/sys/types.h:36:
/Users/arden/Library/Android/sdk/ndk-bundle/sysroot/usr/include/linux/types.h:21:10: fatal error: 'asm/types.h' file not found
#include <asm/types.h>
```

No matter how hard I tried, I had problems, but I was able to work directly with the standard Java platform instead of the android platform.

**Comment by saudet** [comment]
You're missing a "link" value to your platform properties on your class.

And like I said, you'll need to use Clang with NDK r18. GCC is no longer an option.

**Comment by saudet** [comment]
Your CPP_INCLUDEPATH and CPP_INCLUDEPATH_HOME values are for GCC, they are no longer valid for Clang. Either use the default values, or give the right ones.

**Comment by arden** [comment]
I have fainted, now this error:

```
Generating /Users/arden/data/repository/tale/PitayaClientJava/src/main/java/jnijavacpp.cpp
Generating /Users/arden/data/repository/tale/PitayaClientJava/src/main/java/dog/tale/pitaya/jniPitaya.cpp
Compiling /Users/arden/data/repository/tale/PitayaClientJava/src/main/java/lib/armeabi-v7a/libjniPitaya.so
toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -I/Users/arden/data/repository/tale/PitayaClientJava/src/main/cpp/include/ -I/Users/arden/data/source/go/game/libpitaya/src/ /Users/arden/data/repository/tale/PitayaClientJava/src/main/java/dog/tale/pitaya/jniPitaya.cpp /Users/arden/data/repository/tale/PitayaClientJava/src/main/java/jnijavacpp.cpp -mfpu=vfpv3-d16 -O3 -s -Wl,--fix-cortex-a8 -Wl,-rpath,lib/ -D__ANDROID_API__=21 -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -target armv7-none-linux-androideabi -march=armv7-a -mfloat-abi=softfp -Wall -static-libstdc++ -fPIC -shared -Wl,--no-undefined -z text -o libjniPitaya.so -Wl,-soname,libjniPitaya.so -L/Users/arden/data/source/go/game/libpitaya/deps/ -lclang++ -llog -lc++_static -lc++abi -landroid_support -ldl -lm -lc 
Exception in thread "main" java.io.IOException: Cannot run program "toolchains/llvm/prebuilt/linux-x86_64/bin/clang++" (in directory "/Users/arden/data/repository/tale/PitayaClientJava/src/main/java/lib/armeabi-v7a"): error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at org.bytedeco.javacpp.tools.Builder.executeCommand(Builder.java:219)
	at org.bytedeco.javacpp.tools.Builder.compile(Builder.java:463)
	at org.bytedeco.javacpp.tools.Builder.generateAndCompile(Builder.java:578)
	at org.bytedeco.javacpp.tools.Builder.build(Builder.java:1002)
	at org.bytedeco.javacpp.tools.Builder.main(Builder.java:1223)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
```
I know the NDK path in the default android-arm-clang.properties is incorrect, but I don't know how to modify this file and then use the android-arm-clang.properties file I specified.

**Comment by saudet** [comment]
Correct, the "platform.root" is the only property that we usually need to
override. We can do that on the command line with
"-Dplatform.root=/your/path/here"

**Comment by arden** [comment]
`java -jar ../../../lib/javacpp.jar dog.tale.pitaya.Pitaya -properties android-arm-clang -Dplatform.root=/Users/arden/Library/Android/sdk/ndk-bundle -Dplatform.compiler=/Users/arden/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++`

can't find the method defined in the c header file, but I have added the path of c header files in the Java class like this.

```
@Properties(
    target="dog.tale.pitaya.Pitaya",
    value = {
            @Platform(
                    value={""},
                    includepath = {
                            "/Users/arden/data/repository/tale/PitayaClientJava/src/main/cpp/include/",
                            "/Users/arden/data/source/go/game/libpitaya/src/",
                            "/Users/arden/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/",
                            "/Users/arden/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++abi/include/",
                            "/Users/arden/Library/Android/sdk/ndk-bundle/sources/android/support/include/",
                            "/Users/arden/Library/Android/sdk/ndk-bundle/sysroot/usr/include/",
                            "/Users/arden/Library/Android/sdk/ndk-bundle/sysroot/usr/include/arm-linux-androideabi/"
                    },
                    preloadpath = {"/Users/arden/data/source/go/game/libpitaya/deps/"},
                    linkpath = {"/Users/arden/data/source/go/game/libpitaya/deps/"},
                    cinclude = {"pitaya_version.h","pitaya.h"},
                    include = {},
                    library = "jniPitaya"

            )
    }

)
```

```
/var/folders/c9/r7z4rjld7k36nrlgp6q5r2000000gn/T/jniPitaya-90e9ec.o:jniPitaya.cpp:function Java_dog_tale_pitaya_Pitaya_tr_1uv_1tls_1set_1ca_1file__Ljava_lang_String_2Ljava_lang_String_2: error: undefined reference to 'tr_uv_tls_set_ca_file'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
Exception in thread "main" java.lang.RuntimeException: Process exited with an error: 1
	at org.bytedeco.javacpp.tools.Builder.generateAndCompile(Builder.java:594)
	at org.bytedeco.javacpp.tools.Builder.build(Builder.java:1002)
	at org.bytedeco.javacpp.tools.Builder.main(Builder.java:1223)
```

I've been wrestling with this question for a long time.

**Comment by saudet** [comment]
Like I said you're missing a value for @Platform(link=..., ...). You need
to put the filename of your native library there.

**Comment by arden** [comment]
`/Users/arden/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang --sysroot=/Users/arden/Library/Android/sdk/ndk-bundle/platforms/android-21/arch-arm/ -I/Users/arden/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/ -I/Users/arden/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++abi/include/ -I/Users/arden/Library/Android/sdk/ndk-bundle/sources/android/support/include/ -I/Users/arden/Library/Android/sdk/ndk-bundle/sysroot/usr/include/ -I/Users/arden/Library/Android/sdk/ndk-bundle/sysroot/usr/include/arm-linux-androideabi/ -I/Users/arden/data/repository/tale/PitayaClientJava/src/main/cpp/include/ -I/Users/arden/data/source/go/game/libpitaya/src/ /Users/arden/data/repository/tale/PitayaClientJava/src/main/java/dog/tale/pitaya/jniPitaya.cpp /Users/arden/data/repository/tale/PitayaClientJava/src/main/java/jnijavacpp.cpp -mfpu=vfpv3-d16 -O3 -s -Wl,--fix-cortex-a8 -Wl,-rpath,lib/ -D__ANDROID_API__=21 -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -target armv7-none-linux-androideabi -march=armv7-a -mfloat-abi=softfp -Wall -static-libstdc++ -fPIC -shared -Wl,--no-undefined -z text -o libjniPitaya.so -Wl,-soname,libjniPitaya.so -L/Users/arden/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a/ -L/Users/arden/data/source/go/game/libpitaya/src/ -L/Users/arden/data/source/go/game/libpitaya/deps/ -llog -lc++_static -lc++abi -landroid_support -ldl -lm -lc`

`/Users/arden/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang --sysroot=/Users/arden/Library/Android/sdk/ndk-bundle/platforms/android-21/arch-arm/ -I/Users/arden/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/ -I/Users/arden/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++abi/include/ -I/Users/arden/Library/Android/sdk/ndk-bundle/sources/android/support/include/ -I/Users/arden/Library/Android/sdk/ndk-bundle/sysroot/usr/include/ -I/Users/arden/Library/Android/sdk/ndk-bundle/sysroot/usr/include/arm-linux-androideabi/ -I/Users/arden/data/repository/tale/PitayaClientJava/src/main/cpp/include/ -I/Users/arden/data/source/go/game/libpitaya/src/ /Users/arden/data/repository/tale/PitayaClientJava/src/main/java/jnijavacpp.cpp -mfpu=vfpv3-d16 -O3 -s -Wl,--fix-cortex-a8 -Wl,-rpath,lib/ -D__ANDROID_API__=21 -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -target armv7-none-linux-androideabi -march=armv7-a -mfloat-abi=softfp -Wall -static-libstdc++ -fPIC -shared -Wl,--no-undefined -z text -o libjniPitaya.so -Wl,-soname,libjniPitaya.so -L/Users/arden/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a/ -L/Users/arden/data/source/go/game/libpitaya/src/ -L/Users/arden/data/source/go/game/libpitaya/deps/ -llog -lc++_static -lc++abi -landroid_support -ldl -lm -lc`

`/Users/arden/data/repository/tale/PitayaClientJava/src/main/java/dog/tale/pitaya/jniPitaya.cpp /Users/arden/data/repository/tale/PitayaClientJava/src/main/java/jnijavacpp.cpp`

I directly took out the full clang compilation command and analyzed it, and found that there were two jniPitaya.cpp in the command line, I removed the previous one that "dog/tale/pitaya/jniPitaya.cpp", and then recompiled to generate the.so file successfully. I don't understand why two such jniPitaya.cpp files are repeated on the command line.

**Comment by arden** [comment]
```
@Properties(
    target="dog.tale.pitaya.Pitaya",
    value = {
            @Platform(
                    value={""},
                    includepath = {
                            "/Users/arden/data/repository/tale/PitayaClientJava/src/main/cpp/include/",
                            "/Users/arden/data/source/go/game/libpitaya/src/"
                    },
                    preloadpath = {

                    },
                    linkpath = {
                        "/Users/arden/data/repository/tale/PitayaClientJava/lib/",
                    },
                    cinclude = {"pitaya_version.h","pitaya.h"},
                    include = {},
                    library = "jniPitaya",
                    link = "libpitaya-android"
            )
    }

)
```
my native library named libpitaya-android.so in the "/Users/arden/data/repository/tale/PitayaClientJava/lib/", and i'm added a value for @platform(link)，But the problem is the same.

**Comment by saudet** [comment]
For the filename "libpitaya-android.so", the library name is "pitaya-android" so that's that you need to set the `link` value to.

**Comment by arden** [comment]
Thank you very much. It's working now.
