### ISSUE TITLE
no jniNativeLibrary in java.library.path

### ISSUE THREAD

**Issue by whaozl** [bytedeco/javacpp#297]
MultiplyDemo.h
```
#include <string>

namespace NativeLibrary {
    class NativeClass {
        public:
            const std::string& get_property() { return property; }
            void set_property(const std::string& property) { this->property = property; }
            std::string property;
    };
}
```

```
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

@Platform(include= "NativeLibrary.h")
@Namespace("NativeLibrary")
public class NativeLibrary {
    public static class NativeClass extends Pointer {
        static { Loader.load(); }
        public NativeClass() { allocate(); }
        private native void allocate();

        // to call the getter and setter functions
        public native @StdString
        String get_property(); public native void set_property(String property);

        // to access the member variable directly
        public native @StdString String property();    public native void property(String property);
    }

    public static void main(String[] args) {
        // Pointer objects allocated in Java get deallocated once they become unreachable,
        // but C++ destructors can still be called in a timely fashion with Pointer.deallocate()
        NativeClass l = new NativeClass();
        l.set_property("Hello World!");
        System.out.println(l.property());
    }
}
```

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniNativeLibrary in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1336)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1077)
	at org.bytedeco.javacpp.Loader.load(Loader.java:947)
	at NativeLibrary$NativeClass.<clinit>(NativeLibrary.java:12)
	at NativeLibrary.main(NativeLibrary.java:27)
```

The version I quoted maven is

             <dependency>
                <groupId>org.bytedeco</groupId>
                <artifactId>javacpp</artifactId>
                <version>1.5</version>
              </dependency>

**Comment by saudet** [comment]
You'll need to run the Builder. Please follow these instructions:
https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes

**Comment by whaozl** [comment]
Thank you, But I still don't know how to do it, how to use these things under maven in win7 environment. There is no one more complete step.

**Comment by saudet** [comment]
Yes, there is: https://github.com/bytedeco/javacpp-presets/wiki/Create-New-Presets

Let me know if you have any questions about that though.

**Comment by saudet** [comment]
There's also a "helloworld" template that we can refer to here: https://github.com/bytedeco/javacpp-presets/pull/725
