### ISSUE TITLE
Failed to build with maven

### ISSUE THREAD

**Issue by chinadragon0515** [bytedeco/javacpp#33]
In order to rebuild javacv, I need to rebuild javacpp and javacpp-presets, I have installed mingw and add to system path, and when I build the code, I failed to build,  how do I fix this? I uses eclipse Juno with CDT, I find this issue may related http://www.eclipse.org/forums/index.php/t/367773/, but I do not have visual studio, so I wonder whether mingw is enough to build this applicaiton? thanks

[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Not installing Nexus Staging features:
[INFO]  * Preexisting staging related goal bindings found in 1 modules.
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building JavaCPP 1.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ javacpp ---
[INFO] Deleting D:\dev\eclipsews-luna\javacpp-master\target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ javacpp ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 23 resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3:compile (default-compile) @ javacpp ---
[INFO] Compiling 104 source files to D:\dev\eclipsews-luna\javacpp-master\target\classes
[INFO] 
[INFO] --- maven-plugin-plugin:3.2:descriptor (default-descriptor) @ javacpp ---
[INFO] Using 'UTF-8' encoding to read mojo metadata.
[INFO] Applying mojo extractor for language: java
[INFO] Mojo extractor for language: java found 1 mojo descriptors.
[INFO] Applying mojo extractor for language: bsh
[INFO] Mojo extractor for language: bsh found 0 mojo descriptors.
[INFO] Applying mojo extractor for language: java-annotations
[INFO] Mojo extractor for language: java-annotations found 0 mojo descriptors.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ javacpp ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:2.3:testCompile (default-testCompile) @ javacpp ---
[INFO] Compiling 2 source files to D:\dev\eclipsews-luna\javacpp-master\target\test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ javacpp ---
[INFO] Surefire report directory: D:\dev\eclipsews-luna\javacpp-master\target\surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.bytedeco.javacpp.IndexerTest
Generating D:\dev\eclipsews-luna\javacpp-master\target\test-classes\org\bytedeco\javacpp\jniIndexerTest.cpp
Compiling D:\dev\eclipsews-luna\javacpp-master\target\test-classes\org\bytedeco\javacpp\windows-x86_64\jniIndexerTest.dll
cl "/IC:\Program Files\Java\jdk1.8.0_40\include" "/IC:\Program Files\Java\jdk1.8.0_40\include\win32" D:\dev\eclipsews-luna\javacpp-master\target\test-classes\org\bytedeco\javacpp\jniIndexerTest.cpp /W3 /Oi /O2 /EHsc /Gy /GL /MD /LD /link /OUT:D:\dev\eclipsews-luna\javacpp-master\target\test-classes\org\bytedeco\javacpp\windows-x86_64\jniIndexerTest.dll 
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.697 sec <<< FAILURE!
org.bytedeco.javacpp.IndexerTest  Time elapsed: 0.695 sec  <<< ERROR!
java.io.IOException: Cannot run program "cl": CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at org.bytedeco.javacpp.tools.Builder.compile(Builder.java:317)
	at org.bytedeco.javacpp.tools.Builder.generateAndCompile(Builder.java:371)
	at org.bytedeco.javacpp.tools.Builder.build(Builder.java:642)
	at org.bytedeco.javacpp.IndexerTest.setUpClass(IndexerTest.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 25 more

Running org.bytedeco.javacpp.StringTest
Generating D:\dev\eclipsews-luna\javacpp-master\target\test-classes\org\bytedeco\javacpp\jniStringTest.cpp
Compiling D:\dev\eclipsews-luna\javacpp-master\target\test-classes\org\bytedeco\javacpp\windows-x86_64\jniStringTest.dll
cl "/IC:\Program Files\Java\jdk1.8.0_40\include" "/IC:\Program Files\Java\jdk1.8.0_40\include\win32" D:\dev\eclipsews-luna\javacpp-master\target\test-classes\org\bytedeco\javacpp\jniStringTest.cpp /W3 /Oi /O2 /EHsc /Gy /GL /MD /LD /link /OUT:D:\dev\eclipsews-luna\javacpp-master\target\test-classes\org\bytedeco\javacpp\windows-x86_64\jniStringTest.dll 
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.347 sec <<< FAILURE!
org.bytedeco.javacpp.StringTest  Time elapsed: 0.346 sec  <<< ERROR!
java.io.IOException: Cannot run program "cl": CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at org.bytedeco.javacpp.tools.Builder.compile(Builder.java:317)
	at org.bytedeco.javacpp.tools.Builder.generateAndCompile(Builder.java:371)
	at org.bytedeco.javacpp.tools.Builder.build(Builder.java:642)
	at org.bytedeco.javacpp.StringTest.setUpClass(StringTest.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 25 more

Results :

Tests in error: 
  org.bytedeco.javacpp.IndexerTest: Cannot run program "cl": CreateProcess error=2, The system cannot find the file specified
  org.bytedeco.javacpp.StringTest: Cannot run program "cl": CreateProcess error=2, The system cannot find the file specified

Tests run: 2, Failures: 0, Errors: 2, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 27.428 s
[INFO] Finished at: 2015-08-24T15:40:24+08:00
[INFO] Final Memory: 32M/301M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project javacpp: There are test failures.
[ERROR] 
[ERROR] Please refer to D:\dev\eclipsews-luna\javacpp-master\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by chinadragon0515** [comment]
I remove the test code, and build can succeed, so the error impacts the test case.

**Comment by saudet** [comment]
By default MSVC is used as the compiler. We can change that via properties and stuff, but when we're on Windows, we're going to need MSVC as some point or another, so please install it. :)
