### ISSUE TITLE
Platform and Xcompiler options seem to be ignored

### ISSUE THREAD

**Issue by wcork** [bytedeco/javacpp#363]
The following native class is defined:
```Java
@Properties
        ({
@Platform(value={"linux-x86","macosx"}, include={"Pixis.h","<vector>"},
    includepath={"../PixisCPP/src/main/cpp/"}, link={"pthread","dl","raw1394","pvcam","PixisCPP"},
    linkpath={"/usr/local/lib/","/usr/local/lib64/","/opt/local/lib/","/opt/local/lib64/","../SDK/"})
        })
@Name("Pixis")
public final class Pixis_JNI extends Pointer
{
...
```

Project is built using Gradle with the javacpp section:
```Groovy
compileJava.doLast {
    println "javacpp ${project.name} : ${sourceSets.main.compileClasspath.asPath}:${sourceSets.main.runtimeClasspath.asPath}"
    javaexec {
        main 'org.bytedeco.javacpp.tools.Builder'
        classpath "${projectDir}/javacpp/javacpp-${javacppVer}.jar"
        args '-classpath', "${sourceSets.main.compileClasspath.asPath}:${sourceSets.main.runtimeClasspath.asPath}",
                '-properties', 'linux-x86',
                '-d', 'lib/',
                '-o', 'jniPixis',
                'cxro.common.device.camera.Pixis_JNI'
    }
    println 'javacpp done'
}
```

Build output from `gradle build`:
```
Generating /mnt/Data/Development/CXRO/common/devices/pixis/lib/jnijavacpp.cpp
Generating /mnt/Data/Development/CXRO/common/devices/pixis/lib/jniPixis.cpp
Compiling /mnt/Data/Development/CXRO/common/devices/pixis/lib/libjniPixis.so
g++ -I/usr/lib/jvm/java-12-oracle/include -I/usr/lib/jvm/java-12-oracle/include/linux /mnt/Data/Development/CXRO/common/devices/pixis/lib/jniPixis.cpp /mnt/Data/Development/CXRO/common/devices/pixis/lib/jnijavacpp.cpp -march=i686 -m32 -O3 -s -Wl,-rpath,$ORIGIN/ -Wl,-z,noexecstack -Wl,-Bsymbolic -Wall -fPIC -pthread -shared -o libjniPixis.so -L/usr/local/lib/ -Wl,-rpath,/usr/local/lib/ -lPixisCPP -lpvcam -lraw1394 -ldl -lpthread 
/mnt/Data/Development/CXRO/common/devices/pixis/lib/jniPixis.cpp:92:10: fatal error: Pixis.h: No such file or directory
 #include "Pixis.h"
          ^~~~~~~~~
compilation terminated.
Exception in thread "main" java.lang.RuntimeException: Process exited with an error: 1
	at org.bytedeco.javacpp.tools.Builder.generateAndCompile(Builder.java:644)
	at org.bytedeco.javacpp.tools.Builder.build(Builder.java:1107)
	at org.bytedeco.javacpp.tools.Builder.main(Builder.java:1341)
```

Manually executing g++ with proper `-I` and `-L` args produces proper `.so` after code is generated by javacpp.

Manually calling javacpp with `-Xcompiler -I<cpp include path> -L<cpp lib path>` generates same g++ command as above. As if they are ignored.

Something I'm doing wrong?

**Comment by saudet** [comment]
You'll need exactly one `-Xcompiler` per option, so something like this:
```
java -jar javacpp.jar -Xcompiler -I<cpp include path> -Xcompiler -L<cpp lib path> ...
```

**Comment by saudet** [comment]
BTW, a build plugin for Gradle is now available here:
https://github.com/bytedeco/gradle-javacpp
If you try it out and find anything missing, please let me know!
