### ISSUE TITLE
Error Initial the OCR API

### ISSUE THREAD

**Issue by AKMANSoft** [bytedeco/javacpp#377]
On some machines we are getting Error on Tesseract, This occures when creating new instance of 
TessBaseAPI()

`java.util.concurrent.ExecutionException: java.lang.InternalError: Should not get here
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at javax.swing.SwingWorker.get(Unknown Source)
	at com.imviewer.worker.OCRTask.done(OCRTask.java:163)
	at javax.swing.SwingWorker$5.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)
	at sun.swing.AccumulativeRunnable.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)
	at javax.swing.Timer.fireActionPerformed(Unknown Source)
	at javax.swing.Timer$DoPostEvent.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.InternalError: Should not get here
	at sun.nio.fs.WindowsNativeDispatcher.CreateSymbolicLink0(Native Method)
	at sun.nio.fs.WindowsNativeDispatcher.CreateSymbolicLink(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.createSymbolicLink(Unknown Source)
	at java.nio.file.Files.createSymbolicLink(Unknown Source)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1445)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1143)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1042)
	at org.bytedeco.tesseract.global.tesseract.<clinit>(tesseract.java:15)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1109)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1042)
	at org.bytedeco.tesseract.TessBaseAPI.<clinit>(TessBaseAPI.java:25)
	at com.imviewer.worker.OCRTask$OCRChecker.<init>(OCRTask.java:182)
	at com.imviewer.worker.OCRTask.doInBackground(OCRTask.java:80)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)`

**Comment by saudet** [comment]
Looks like a bug in the JDK. Try another version of the JDK?

**Comment by saudet** [comment]
Does this occur with Oracle JDK 8, Oracle JDK 11, OpenJDK 8, and OpenJDK 11, on Linux, Mac, and Windows?

**Comment by AKMANSoft** [comment]
We are using Open JDK 11, using Widows 10,

**Comment by saudet** [comment]
Please also try with JDK 8.

**Comment by saudet** [comment]
If this problem doesn't occur with JDK 8, please file a bug report probably here:
https://bugreport.java.com/bugreport/

**Comment by saudet** [comment]
Any updates? Does this still happen with OpenJDK 14?
