### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no jniopencv_core in java.library.path

### ISSUE THREAD

**Issue by Grisi** [bytedeco/javacpp#42]
hi @saudet ,
Im getting this error, i read all the issues with the same error here and i was wondering if you could tell me what exactly do i have to include in java.library.path
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopencv_core in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1886)
	at java.lang.Runtime.loadLibrary0(Runtime.java:849)
	at java.lang.System.loadLibrary(System.java:1088)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:550)
	at org.bytedeco.javacpp.Loader.load(Loader.java:415)
	at org.bytedeco.javacpp.Loader.load(Loader.java:358)
	at org.bytedeco.javacpp.opencv_core.<clinit>(opencv_core.java:10)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:274)
	at org.bytedeco.javacpp.Loader.load(Loader.java:390)
	at org.bytedeco.javacpp.Loader.load(Loader.java:358)
	at org.bytedeco.javacpp.opencv_imgcodecs.<clinit>(opencv_imgcodecs.java:13)
	at FaceDetect.main(FaceDetect.java:41)
```
Thank you!

**Comment by saudet** [comment]
Just try to include all of the JAR files and let's see what that gives.

**Comment by saudet** [comment]
Did including all the JAR files in your class path fix this issue?

**Comment by Grisi** [comment]
Yes, it did! Thank you.

**Comment by saudet** [comment]
Great! Thanks for the feedback

**Comment by bfoust** [comment]
How did "including all the JAR files" entail?

**Comment by bfoust** [comment]
What did "include all the JAR files" entail?

**Comment by Grisi** [comment]
I actually had the lib of opencv on the system path, the problem was that opencv was missing some dependencies, including all the jars did solve my problem. there are some jars(javacpp, opencv etc..) that are inside opencv, include all of them in your project. hope that helps

**Comment by jinghao17** [comment]
hi @saudet 
i have the same problem and im beginner...  can teach me step by step to solve ?
![123](https://user-images.githubusercontent.com/37212499/39031030-7612926e-4498-11e8-85c2-fda8b96143c9.PNG)

**Comment by saudet** [comment]
@jinghao17 Start here: https://github.com/bytedeco/javacv#downloads

**Comment by jinghao17** [comment]
After file>Project structure>"""""app""""" i don have app in my intelliJ 
![121212](https://user-images.githubusercontent.com/37212499/39037830-45dd615c-44b4-11e8-9313-ac999b671195.PNG)

**Comment by saudet** [comment]
That's for Android. For desktop just do as you would do with JAR files.

**Comment by jinghao17** [comment]
ok thank Q...
