### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no jnijavacpp in java.library.path

### ISSUE THREAD

**Issue by mengpengfei** [bytedeco/javacpp#422]
I execute 2 command: 
java -jar javacpp-1.5.3.jar YoloConfig.java
java -jar javacpp-1.5.3.jar Yolo.java

The 2 command had executed successfully,and i got the Yolo.java and the linux-x86_64 directory with the libjniYolo.so

but when i call a function of Yolo.java,error occurs

Warning: Could not load Loader: java.lang.UnsatisfiedLinkError: no jnijavacpp in java.library.path
Exception in thread "main" java.lang.NoClassDefFoundError: java.lang.ClassNotFoundException: Yolo
        at org.bytedeco.javacpp.Loader.load(Loader.java:1181)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1109)
        at com.zhidao.yolo.Yolo.<clinit>(Yolo.java:8)
        at com.zhidao.test.YoloTest.main(YoloTest.java:19)
Caused by: java.lang.ClassNotFoundException: Yolo
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1176)
        ... 3 more

![image](https://user-images.githubusercontent.com/13211758/90489328-b6a35b80-e16f-11ea-94f5-350da10238af.png)
![image](https://user-images.githubusercontent.com/13211758/90489412-d470c080-e16f-11ea-989c-c3d00c295441.png)

please help me

**Comment by saudet** [comment]
Classes without package names cannot be accessed from classes with package
names, that's normal.

**Comment by mengpengfei** [comment]
can you tell me how can i use javacpp with package?thanks

**Comment by saudet** [comment]
We just need to make sure to put all classes in packages, like this:
https://docs.oracle.com/javase/tutorial/java/package/packages.html
