### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no jniai_basketball in java.library.path

### ISSUE THREAD

**Issue by lichuanjun** [bytedeco/javacpp#431]
I use javacpp-presets output ai_basketball-1.0.0-macosx.jar and ai_basketball-1.0.0.jar， then I import the two jar in my project which use maven。code like:
```
 @Test
    public void testJavaCpp() {
        AIBASKETBALL_HANDLE basketballEngine = new AIBASKETBALL_HANDLE();
        AIbasketballConfig config = new AIbasketballConfig();
        config.threeSecondAreaType(1);
}
```
But it throw error when ```Loader.load()```. error message like:
```
java.lang.UnsatisfiedLinkError: no jniai_basketball in java.library.path

	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1683)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1300)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1123)
	at org.bytedeco.ai_basketball.global.ai_basketball.<clinit>(ai_basketball.java:18)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1190)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1123)
	at org.bytedeco.ai_basketball.AIbasketballConfig.<clinit>(AIbasketballConfig.java:20)
	at com.alisports.video.JavaCVTest.testJavaCpp(JavaCVTest.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.UnsatisfiedLinkError: /Users/lcj/.javacpp/cache/ai_basketball-1.0.0-macosx.jar/org/bytedeco/ai_basketball/macosx-x86_64/libjniai_basketball.dylib: dlopen(/Users/lcj/.javacpp/cache/ai_basketball-1.0.0-macosx.jar/org/bytedeco/ai_basketball/macosx-x86_64/libjniai_basketball.dylib, 1): Symbol not found: _icv_ippJumpIndexForMergedLibs
  Referenced from: /usr/local/opt/opencv/lib/libopencv_imgproc.4.4.dylib
  Expected in: /Users/lcj/.javacpp/cache/opencv-4.4.0-1.5.4-macosx-x86_64.jar/org/bytedeco/opencv/macosx-x86_64/libopencv_core.4.4.dylib
 in /usr/local/opt/opencv/lib/libopencv_imgproc.4.4.dylib
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1633)
	... 31 more


Disconnected from the target VM, address: '127.0.0.1:50081', transport: 'socket'

Process finished with exit code 255
```

what is the meaning of ```Symbol not found: _icv_ippJumpIndexForMergedLibs
  Referenced from: /usr/local/opt/opencv/lib/libopencv_imgproc.4.4.dylib
  Expected in: /Users/lcj/.javacpp/cache/opencv-4.4.0-1.5.4-macosx-x86_64.jar/org/bytedeco/opencv/macosx-x86_64/libopencv_core.4.4.dylib```, I checked all the path like ```/usr/local/opt/opencv/lib/libopencv_imgproc.4.4.dylib``` and  ```/Users/lcj/.javacpp/cache/opencv-4.4.0-1.5.4-macosx-x86_64.jar/org/bytedeco/opencv/macosx-x86_64/libopencv_core.4.4.dylib``` etc listed in the error info. all of them existed.

**Comment by saudet** [comment]
Look like you're building OpenCV against IPP. You'll need to make sure it's available at runtime as well.

**Comment by lichuanjun** [comment]
> Look like you're building OpenCV against IPP. You'll need to make sure it's available at runtime as well.

I use javacv and javacpp. my pom.xml as follow:
```
            <dependency>
                <groupId>org.bytedeco</groupId>
                <artifactId>javacv-platform</artifactId>
                <version>1.5.4</version>
            </dependency>

            <dependency>
                <groupId>org.bytedeco</groupId>
                <artifactId>javacpp</artifactId>
                <version>1.5.4</version>
            </dependency>
```

**Comment by saudet** [comment]
That's OK, but if you build OpenCV with IPP, you also need to run it with
IPP. If you do not want to need IPP when running, then please, do not build
OpenCV with IPP.

**Comment by lichuanjun** [comment]
> That's OK, but if you build OpenCV with IPP, you also need to run it with IPP. If you do not want to need IPP when running, then please, do not build OpenCV with IPP.

> That's OK, but if you build OpenCV with IPP, you also need to run it with IPP. If you do not want to need IPP when running, then please, do not build OpenCV with IPP.

I donot know how to build opencv with IPP and why it comes with IPP. I know nothing about IPP. 
I just have a C++ library and header files  which depend on opencv and I build it with javacpp-presets as link: https://github.com/bytedeco/javacpp-presets/wiki/Create-New-Presets

**Comment by saudet** [comment]
Ok, then remove the copy of OpenCV in /usr/local/opt/opencv.

**Comment by lichuanjun** [comment]
> /usr/local/opt/opencv

Yes，I delete the ```/usr/local/opt/opencv```. But it throw another error:
```
java.lang.UnsatisfiedLinkError: /Users/lcj/Desktop/work/javacpp-presets/ai_basketball/target/native/org/bytedeco/ai_basketball/macosx-x86_64/libjniai_basketball.dylib: dlopen(/Users/lcj/Desktop/work/javacpp-presets/ai_basketball/target/native/org/bytedeco/ai_basketball/macosx-x86_64/libjniai_basketball.dylib, 1): Library not loaded: /usr/local/opt/opencv/lib/libopencv_gapi.4.4.dylib
  Referenced from: /Users/lcj/Desktop/work/sportsai_basketball/bin/libsportsai_basketball.dylib
  Reason: image not found

	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1683)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1300)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1123)
	at org.bytedeco.ai_basketball.global.ai_basketball.<clinit>(ai_basketball.java:18)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1190)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1123)
	at org.bytedeco.ai_basketball.AIbasketballConfig.<clinit>(AIbasketballConfig.java:20)
	at com.alisports.video.JavaCVTest.testJavaCpp(JavaCVTest.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.UnsatisfiedLinkError: /Users/lcj/.javacpp/cache/ai_basketball-1.0.0-macosx.jar/org/bytedeco/ai_basketball/macosx-x86_64/libjniai_basketball.dylib: dlopen(/Users/lcj/.javacpp/cache/ai_basketball-1.0.0-macosx.jar/org/bytedeco/ai_basketball/macosx-x86_64/libjniai_basketball.dylib, 1): Library not loaded: /usr/local/opt/opencv/lib/libopencv_gapi.4.4.dylib
  Referenced from: /Users/lcj/Desktop/work/sportsai_basketball/bin/libsportsai_basketball.dylib
  Reason: image not found
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1633)
	... 31 more
```

It means  the project need opencv and I cannot just remove it?

**Comment by saudet** [comment]
You'll need to link your library against a non-broken version of OpenCV. Since you'll be using it with the version of OpenCV from the presets, it is recommended to link your library with that version of OpenCV that comes with the presets.

**Comment by saudet** [comment]
See https://github.com/bytedeco/javacpp-presets/issues/965
