### ISSUE TITLE
Cross platform build

### ISSUE THREAD

**Issue by miloradtrninic** [bytedeco/javacpp#435]
I am using Ubuntu 20.04 to build my which was developed 4 years ago and it is using old libs. Before maven I was adding jars manually into the classpath. Now when I use maven my far JAR doesn't come with .SO files for other platforms only with linux-x86_64.

Here is my pom:
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>WebScraper</groupId>
  <artifactId>WebScraper</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <build>
    <sourceDirectory>src</sourceDirectory>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.0</version>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
        </configuration>
      </plugin>
      
	  <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-assembly-plugin</artifactId>
            <version>3.1.1</version>
		    <configuration>
		      <archive>
		        <manifest>
		          <addClasspath>true</addClasspath>
		          <mainClass>view.webscraperScraperHTMLGUIe</mainClass>
		        </manifest>
		      </archive>
		      <descriptorRefs>
		        <descriptorRef>jar-with-dependencies</descriptorRef>
		      </descriptorRefs>
		    </configuration>
            <executions>
                <execution>
                    <id>make-assembly</id>
                    <phase>package</phase>
                    <goals>
                        <goal>single</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>
    </plugins>
  </build>
    <dependency>
      <groupId>org.jsoup</groupId>
      <artifactId>jsoup</artifactId>
      <version>1.9.2</version>
    </dependency>
    <dependency>
     <groupId>org.bytedeco</groupId>
      <artifactId>javacpp</artifactId>
      <version>1.1</version>
    </dependency>
    <dependency>
      <groupId>org.bytedeco</groupId>
      <artifactId>javacv</artifactId>
      <version>1.1</version>
    </dependency>

  </dependencies>
</project>
```
So when I do the `clean package` in order to get a fat JAR I am ending up with .SO libraries only for linux and I want to get .SO for other systems as well. Is this even possible without running the build on other OS?

**Comment by miloradtrninic** [comment]
UPDATE: I tried build on Windows 7 x64 also and it works there, but when I try my software on Windows Server 2012 R2 I get error:
```
Exception in thread "pool-1-thread-2" Exception in thread "pool-1-thread-1" java
.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.avut
il
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at org.bytedeco.javacpp.Loader.load(Loader.java:413)
        at org.bytedeco.javacpp.Loader.load(Loader.java:381)
        at org.bytedeco.javacpp.avformat$AVFormatContext.<clinit>(avformat.java:
2597)
        at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber
.java:386)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:
380)
        at services.ScreenshotGrab.makeScreens(ScreenshotGrab.java:120)
        at services.ScreenshotGrab.run(ScreenshotGrab.java:71)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Exception in thread "pool-1-thread-12" Exception in thread "pool-1-thread-11" ja
va.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.av
format$AVFormatContext
        at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber
.java:386)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:
380)
        at services.ScreenshotGrab.makeScreens(ScreenshotGrab.java:120)
        at services.ScreenshotGrab.run(ScreenshotGrab.java:71)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Exception in thread "pool-1-thread-10" Exception in thread "pool-1-thread-9" Exc
eption in thread "pool-1-thread-8" Exception in thread "pool-1-thread-7" Excepti
on in thread "pool-1-thread-6" Exception in thread "pool-1-thread-5" Exception i
n thread "pool-1-thread-3" Exception in thread "pool-1-thread-4" java.lang.NoCla
ssDefFoundError: Could not initialize class org.bytedeco.javacpp.avformat$AVForm
atContext
        at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber
.java:386)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:
380)
        at services.ScreenshotGrab.makeScreens(ScreenshotGrab.java:120)
        at services.ScreenshotGrab.run(ScreenshotGrab.java:71)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.
avformat$AVFormatContext
        at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber
.java:386)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:
380)
        at services.ScreenshotGrab.makeScreens(ScreenshotGrab.java:120)
        at services.ScreenshotGrab.run(ScreenshotGrab.java:71)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.
avformat$AVFormatContext
        at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber
.java:386)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:
380)
        at services.ScreenshotGrab.makeScreens(ScreenshotGrab.java:120)
        at services.ScreenshotGrab.run(ScreenshotGrab.java:71)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.
avformat$AVFormatContext
        at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber
.java:386)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:
380)
        at services.ScreenshotGrab.makeScreens(ScreenshotGrab.java:120)
        at services.ScreenshotGrab.run(ScreenshotGrab.java:71)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.
avformat$AVFormatContext
        at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber
.java:386)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:
380)
        at services.ScreenshotGrab.makeScreens(ScreenshotGrab.java:120)
        at services.ScreenshotGrab.run(ScreenshotGrab.java:71)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.
avformat$AVFormatContext
        at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber
.java:386)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:
380)
        at services.ScreenshotGrab.makeScreens(ScreenshotGrab.java:120)
        at services.ScreenshotGrab.run(ScreenshotGrab.java:71)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.
avformat$AVFormatContext
        at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber
.java:386)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:
380)
        at services.ScreenshotGrab.makeScreens(ScreenshotGrab.java:120)
        at services.ScreenshotGrab.run(ScreenshotGrab.java:71)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.
avformat$AVFormatContext
        at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber
.java:386)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:
380)
        at services.ScreenshotGrab.makeScreens(ScreenshotGrab.java:120)
        at services.ScreenshotGrab.run(ScreenshotGrab.java:71)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.
avformat$AVFormatContext
        at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber
.java:386)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:
380)
        at services.ScreenshotGrab.makeScreens(ScreenshotGrab.java:120)
        at services.ScreenshotGrab.run(ScreenshotGrab.java:71)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Exception in thread "pool-1-thread-18" Exception in thread "pool-1-thread-17" Ex
ception in thread "pool-1-thread-16" Exception in thread "pool-1-thread-15" Exce
ption in thread "pool-1-thread-14" Exception in thread "pool-1-thread-13" java.l
ang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.avform
at$AVFormatContext
        at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber
.java:386)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:
380)
        at services.ScreenshotGrab.makeScreens(ScreenshotGrab.java:120)
        at services.ScreenshotGrab.run(ScreenshotGrab.java:71)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.
avformat$AVFormatContext
        at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber
.java:386)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:
380)
        at services.ScreenshotGrab.makeScreens(ScreenshotGrab.java:120)
        at services.ScreenshotGrab.run(ScreenshotGrab.java:71)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.
avformat$AVFormatContext
        at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber
.java:386)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:
380)
        at services.ScreenshotGrab.makeScreens(ScreenshotGrab.java:120)
        at services.ScreenshotGrab.run(ScreenshotGrab.java:71)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.
avformat$AVFormatContext
        at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber
.java:386)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:
380)
        at services.ScreenshotGrab.makeScreens(ScreenshotGrab.java:120)
        at services.ScreenshotGrab.run(ScreenshotGrab.java:71)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.
avformat$AVFormatContext
        at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber
.java:386)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:
380)
        at services.ScreenshotGrab.makeScreens(ScreenshotGrab.java:120)
        at services.ScreenshotGrab.run(ScreenshotGrab.java:71)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.
avformat$AVFormatContext
        at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber
.java:386)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:
380)
        at services.ScreenshotGrab.makeScreens(ScreenshotGrab.java:120)
        at services.ScreenshotGrab.run(ScreenshotGrab.java:71)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.
avformat$AVFormatContext
        at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber
.java:386)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:
380)
        at services.ScreenshotGrab.makeScreens(ScreenshotGrab.java:120)
        at services.ScreenshotGrab.run(ScreenshotGrab.java:71)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
``

**Comment by miloradtrninic** [comment]
Found a solution, thanks to last comment on #106 it has to be dependency with "-platform" sufix.
