### ISSUE TITLE
Issue with Thrust Example

### ISSUE THREAD

**Issue by masterav10** [bytedeco/javacpp#485]
Trying to get this working:
https://github.com/bytedeco/javacpp/wiki/Interface-Thrust-and-CUDA

Everything seems to compile as expected. However, when I go to run the main application, I get the following error:

```
java.lang.RuntimeException: radix_sort: failed on 1st step: cudaErrorInvalidDeviceFunction: invalid device function
    at thrust.Thrust.sort(Native Method)
    at thrust.JavacppSampleTest.verifySample(JavacppSampleTest.java:25)
```
From the NVIDIA docs:
`cudaErrorInvalidDeviceFunction = 98`
> The requested device function does not exist or is not compiled for the proper device architecture.

I tried experimenting with different architectures, but to no avail. I've created a sample project with a unit test that demonstrates the problem here:
> https://github.com/masterav10/thrust

Toolchain:
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2021 NVIDIA Corporation
> Built on Sun_Feb_14_22:08:44_Pacific_Standard_Time_2021
> Cuda compilation tools, release 11.2, V11.2.152
> Build cuda_11.2.r11.2/compiler.29618528_0

> Microsoft (R) C/C++ Optimizing Compiler Version 19.27.29111 for x64

Steps to recreate:
1) Clone my 'thrust' project
2) Run x64 Native Tools Command Prompt for VS 2019
3) Navigate to the thrust project
4) gradlew clean test

**Comment by saudet** [comment]
It looks like recent versions of Thrust don't like the `/GL` option from MSVC. It works fine if we disable it, for example, this way:
```bash
java -jar javacpp.jar ThrustTest.java -properties windows-x86_64-cuda -Xcompiler -Xcompiler=-GL-
```
We would need someone to investigate why this happens and how it should be fixed... In any case, thanks for reporting!

**Comment by masterav10** [comment]
Verified it is now working on my machine with the provided flag. Much appreciated Sam!

Looks like a similar issue has been reported in the Thrust repo:
> https://github.com/NVIDIA/thrust/issues/1127

I'm not sure if the issue is nvcc, cl, or thrust.

In Cuda Samples, under 6_Advanced, there is a thrust examples called radixSortThrust. I verified that /GL causes the program to fail when running in config Release x64. It doesn't fail when running Debug x64, which is somewhat surprising although I imagine optimization is far less aggressive when compiling in Debug. The same problem with both VS 2017 and VS 2019.
