### ISSUE TITLE
UnsatisfiedLinkError: no jnijavacpp in java.library.path

### ISSUE THREAD

**Issue by yamert89** [bytedeco/javacpp#524]
I have DEMODLL.dll with simple code:
_Demodll.h_
```
#pragma once
#ifdef DEMO_EXPORTS
#define DEMO_API __declspec(dllexport)
#else
#define DEMO_API __declspec(dllimport)
#endif
#include <string>
using namespace std;
namespace Demo {
	class Demo1 {
	public: DEMO_API void printProc2();
	};
}
```
_Demodll.cpp_
```
#include "pch.h"
#include <iostream>
#include "Demodll.h"
#include <Windows.h>
#include <sysinfoapi.h>

using namespace std;

void Demo::Demo1::printProc2() {
    SYSTEM_INFO info;
    GetSystemInfo(&info);
    cout << info.dwNumberOfProcessors << endl;
}
```
and java class:
_Demo.java_

```
package demo;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.Namespace;
import org.bytedeco.javacpp.annotation.Platform;
@Platform(linkpath = "DEMODLL.DLL",
include = {"Demodll.h"})
@Namespace("Demo")
public class Demo {
    public static class Demo1{
        static {
            Loader.load();
        }
        public Demo1(){allocate();}
        native void printProc2();
        private native void allocate();
    }

    public static void main(String[] args) {
        try{
            new Demo.Demo1().printProc2();
        }catch (Exception e){
            e.printStackTrace();
        }

    }
}
```
I compile this with: 
```
javac -cp javacpp-1.5.6.jar demo/Demo.java
java -jar javacpp-1.5.6.jar demo.Demo
```
The process success finished. But when i run my Demo.jar this crashes with warning
`Could not load Loader: java.lang.UnsatisfiedLinkError: no jnijavacpp in java.library.path: C:\Program Files\Java\jdk-17.0.1\bin; ... etc.`
and exception

```
 at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2429)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
        at java.base/java.lang.System.loadLibrary(System.java:1989)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1718)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1328)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1132)
        at demo.Demo$Demo1.<clinit>(Demo.java:12)
        at demo.Demo.main(Demo.java:21)
```

**Comment by saudet** [comment]
The value for `@Platform(link=...)` is missing. That's probably not going to work without it.

**Comment by yamert89** [comment]
I put DEMODLL.DLL, Demodll.lib and Demodll.h to _"C:/localrepo"_ and change mapping as:
```
@Platform(
        link = "DEMODLL",
        linkpath = "C:/localrepo",
        include = "Demodll.h",
        includepath = "C:/localrepo")
@Namespace("Demo")
public class Demo {
```
but still get the same problem.

**Comment by saudet** [comment]
It sounds like you're not including the native libraries in your JAR file. What is the content of your JAR file?

**Comment by yamert89** [comment]
_Demo.jar_
![Снимок](https://user-images.githubusercontent.com/38682240/140269681-b993afe2-3f91-4e93-a434-66e286f5c739.JPG)
If i pass the path with generated files across -Djava.library.path, jar throws
```
Warning: Could not load Loader: java.lang.UnsatisfiedLinkError: no jnijavacpp in java.library.path: K:\coding\Native\lib\windows-x86_64
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'void demo.Demo$Demo1.printProc2()'
        at demo.Demo$Demo1.printProc2(Native Method)
        at demo.Demo.main(Demo.java:24)
```

**Comment by saudet** [comment]
The DLL needs to be packaged in a subdirectory named after your platform.
JavaCPP does that by default, so don't try to move it. It won't work in the
root like that.

**Comment by yamert89** [comment]
I done
![Снимок](https://user-images.githubusercontent.com/38682240/140275134-e616e57c-f2ff-480d-a8d6-8a1b659a6fd1.JPG)
but still doesnt work
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'void demo.Demo$Demo1.printProc2()'
        at demo.Demo$Demo1.printProc2(Native Method)
        at demo.Demo.main(Demo.java:24)
```
DEMODLL.dll work from another c++ program

**Comment by saudet** [comment]
You'll need to make sure that `Loader.load(Demo.class)` gets called to actually load the DLL.

**Comment by yamert89** [comment]
Loader.load(Demo.class) -> C:\Users\--user name--\.javacpp\cache\Demo.jar\windows-x86_64\jniDemo.dll

**Comment by saudet** [comment]
`java -jar javacpp-1.5.6.jar demo.Demo` is probably not going to do anything. As per the docs, try to call `java -jar javacpp-1.5.6.jar demo` instead. Please don't try to deviate from the docs!

**Comment by saudet** [comment]
Actually, demo.Demo should be alright. Let's see, please set the "org.bytedeco.javacpp.logger.debug" system property to get more information on the console.

**Comment by yamert89** [comment]
I made demo.Demo because
java -jar javacpp-1.5.6.jar Demo from src/java  throws java.lang.ClassNotFoundException: Demo  or 
 from src/java/demo throws java.lang.NoClassDefFoundError: demo/Demo (wrong name: Demo)

debug output:
```
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.javacpp.Loader
Debug: Loading C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-crt-locale-l1-1-0.dll
Debug: Loading C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-crt-string-l1-1-0.dll
Debug: Loading C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-crt-stdio-l1-1-0.dll
Debug: Loading C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-crt-math-l1-1-0.dll
Debug: Loading C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-crt-heap-l1-1-0.dll
Debug: Loading C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-crt-runtime-l1-1-0.dll
Debug: Loading C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-crt-convert-l1-1-0.dll
Debug: Loading C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-crt-environment-l1-1-0.dll
Debug: Loading C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-crt-time-l1-1-0.dll
Debug: Loading C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-crt-filesystem-l1-1-0.dll
Debug: Loading C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-crt-utility-l1-1-0.dll
Debug: Loading C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-crt-multibyte-l1-1-0.dll
Debug: Loading C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-core-string-l1-1-0.dll
Debug: Loading C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-core-errorhandling-l1-1-0.dll
Debug: Loading C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-core-timezone-l1-1-0.dll
Debug: Loading C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-core-file-l1-1-0.dll
Debug: Loading C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-core-namedpipe-l1-1-0.dll
Debug: Loading C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-core-handle-l1-1-0.dll
Debug: Loading C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-core-file-l2-1-0.dll
Debug: Loading C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-core-heap-l1-1-0.dll
Debug: Loading C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-core-libraryloader-l1-1-0.dll
Debug: Loading C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-core-synch-l1-1-0.dll
Debug: Loading C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-core-processthreads-l1-1-0.dll
Debug: Loading C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-core-processenvironment-l1-1-0.dll
Debug: Loading C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-core-datetime-l1-1-0.dll
Debug: Loading C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-core-localization-l1-2-0.dll
Debug: Loading C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-core-sysinfo-l1-1-0.dll
Debug: Loading C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-core-synch-l1-2-0.dll
Debug: Loading C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-core-console-l1-1-0.dll
Debug: Loading C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-core-debug-l1-1-0.dll
Debug: Loading C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-core-rtlsupport-l1-1-0.dll
Debug: Loading C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-core-processthreads-l1-1-1.dll
Debug: Loading C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-core-file-l1-2-0.dll
Debug: Loading C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-core-profile-l1-1-0.dll
Debug: Loading C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-core-memory-l1-1-0.dll
Debug: Loading C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-core-util-l1-1-0.dll
Debug: Loading C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-core-interlocked-l1-1-0.dll
Debug: Loading C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\ucrtbase.dll
Debug: Loading library vcruntime140
Debug: Loading library vcruntime140_1
Debug: Loading library msvcp140
Debug: Loading library msvcp140_1
Debug: Loading library concrt140
Debug: Loading library vcomp140
Debug: Loading library jnijavacpp
Debug: Failed to load for jnijavacpp: java.lang.UnsatisfiedLinkError: no jnijavacpp in java.library.path: C:\Program Files\Java\jdk-17.0.1\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Common Files\Acronis\SnapAPI\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\JetBrains\IntelliJ IDEA 2019.1.2\plugins\maven\lib\maven3\bin;C:\Program Files\PuTTY\;C:\Program Files\Java\jdk-11.0.4\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Windows Kits\10\Redist\10.0.19041.0\ucrt\DLLs\x64;C:\localrepo;C:\Users\Пендальф Синий\AppData\Local\Microsoft\WindowsApps;C:\Program Files\JetBrains\IntelliJ IDEA 2019.1.2\bin;C:\Users\Пендальф Синий\AppData\Local\Programs\Fiddler;C:\Program Files\JetBrains\IntelliJ IDEA 2020.1\bin;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.1\bin;C:\Users\Пендальф Синий\AppData\Local\Programs\Microsoft VS Code\bin;.
Warning: Could not load Loader: java.lang.UnsatisfiedLinkError: no jnijavacpp in java.library.path: C:\Program Files\Java\jdk-17.0.1\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Common Files\Acronis\SnapAPI\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\JetBrains\IntelliJ IDEA 2019.1.2\plugins\maven\lib\maven3\bin;C:\Program Files\PuTTY\;C:\Program Files\Java\jdk-11.0.4\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Windows Kits\10\Redist\10.0.19041.0\ucrt\DLLs\x64;C:\localrepo;C:\Users\Пендальф Синий\AppData\Local\Microsoft\WindowsApps;C:\Program Files\JetBrains\IntelliJ IDEA 2019.1.2\bin;C:\Users\Пендальф Синий\AppData\Local\Programs\Fiddler;C:\Program Files\JetBrains\IntelliJ IDEA 2020.1\bin;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.1\bin;C:\Users\Пендальф Синий\AppData\Local\Programs\Microsoft VS Code\bin;.
Debug: Loading class demo.Demo
Debug: Loading C:\localrepo\DEMODLL.dll
Debug: Creating symbolic link C:\Users\Пендальф Синий\.javacpp\cache\Demo.jar\windows-x86_64\DEMODLL.dll to C:\localrepo\DEMODLL.dll
Debug: Loading C:\Users\Пендальф Синий\.javacpp\cache\Demo.jar\windows-x86_64\jniDemo.dll
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.javacpp.Pointer
Demo : C:\Users\Пендальф Синий\.javacpp\cache\Demo.jar\windows-x86_64\jniDemo.dll
Debug: Loading class demo.Demo
Debug: Loading class demo.Demo$Demo1
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'void demo.Demo$Demo1.printProc2()'
        at demo.Demo$Demo1.printProc2(Native Method)
        at demo.Demo.main(Demo.java:36)
```

**Comment by saudet** [comment]
What is the content of jniDemo.cpp?

**Comment by yamert89** [comment]
I dont have it. When i compile with javacpp.jar  console write this:
```
Info: Deleting K:\coding\Native\src\main\java\demo\jniDemo.cpp
Info: Deleting K:\coding\Native\src\main\java\jnijavacpp.cpp
```

**Comment by saudet** [comment]
Run with the -nodelete option

**Comment by saudet** [comment]
Ah, here's the problem: Demo1 isn't a subclass of Pointer. JavaCPP ignores any such classes. Please follow the instructions in the documentation. Doing things randomly like this isn't productive.

**Comment by yamert89** [comment]
Thank you!
