### ISSUE TITLE
Tesseract: java.lang.RuntimeException: std::bad_alloc When running on Azure Functions App

### ISSUE THREAD

**Issue by pure-zero** [bytedeco/javacpp#579]
Hi there, I was wondering if you have seen this issue I am getting when deploying Tesseract onto an Azure Functions app.

Am I missing a configuration or something here?

Here is the code I am trying to deploy. https://github.com/pure-zero/test-javacpp-tesseract-azure-functions

2022-06-09T01:03:33Z   [Information]   java.lang.RuntimeException: std::bad_alloc
2022-06-09T01:03:33Z   [Information]   	at org.bytedeco.tesseract.TessBaseAPI.Init(Native Method)
2022-06-09T01:03:33Z   [Information]   	at io.quarkus.GreetingVertx.hello(GreetingVertx.java:26)
2022-06-09T01:03:33Z   [Information]   	at io.quarkus.GreetingVertx_RouteHandler_hello_118b601b1064e98034f721f9c2515f60ab038c79.invoke(Unknown Source)
2022-06-09T01:03:33Z   [Information]   	at io.quarkus.vertx.web.runtime.RouteHandler.handle(RouteHandler.java:97)
2022-06-09T01:03:33Z   [Information]   	at io.quarkus.vertx.web.runtime.RouteHandler.handle(RouteHandler.java:22)
2022-06-09T01:03:33Z   [Information]   	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
2022-06-09T01:03:33Z   [Information]   	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:126)
2022-06-09T01:03:33Z   [Information]   	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:201)
2022-06-09T01:03:33Z   [Information]   	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$23.handle(VertxHttpRecorder.java:1395)
2022-06-09T01:03:33Z   [Information]   	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$23.handle(VertxHttpRecorder.java:1364)
2022-06-09T01:03:33Z   [Information]   	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
2022-06-09T01:03:33Z   [Information]   	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
2022-06-09T01:03:33Z   [Information]   	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:201)
2022-06-09T01:03:33Z   [Information]   	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:412)
2022-06-09T01:03:33Z   [Information]   	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:390)
2022-06-09T01:03:33Z   [Information]   	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
2022-06-09T01:03:33Z   [Information]   	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
2022-06-09T01:03:33Z   [Information]   	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:201)
2022-06-09T01:03:33Z   [Information]   	at io.vertx.ext.web.impl.RouterImpl.handleContext(RouterImpl.java:248)
2022-06-09T01:03:33Z   [Information]   	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
2022-06-09T01:03:33Z   [Information]   	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
2022-06-09T01:03:33Z   [Information]   	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
2022-06-09T01:03:33Z   [Information]   	at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:67)

Thanks a lot.

**Comment by saudet** [comment]
That error usually means that it was unable to allocate memory, so you're probably just running out of memory.

**Comment by pure-zero** [comment]
Thanks, that is not referring to JVM memory right? 

This is occurring when running if (api.Init("/home/site/wwwroot/bin/tessdata", "eng") != 0) {

I have tried this on an azure function machine with 16gb memory before though, I will see if I can try it with the above project

**Comment by saudet** [comment]
> Thanks, that is not referring to JVM memory right?

Yes, that's right: https://en.cppreference.com/w/cpp/memory/new/bad_alloc
