### ISSUE TITLE
java.io.IOException: Cannot run program "/app/.javacpp/cache/ffmpeg-5.0-1.5.7-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/ffmpeg": error=2, No such file or directory

### ISSUE THREAD

**Issue by shourya93** [bytedeco/javacpp#583]
Hi, I have updated the docker image to **openjdk17:17.0.3.07.08 from Java8**. Since then the application has been throwing up different errors which somehow I was able to resolve but I got stuck with one error described here and desperately looking for any help.

So basically, I have changed the Java17 image URL in the docker file and taken a Jenkins build and deploying it to the Openshift. The pod is getting created successfully but at the time of application start up getting the below error.

Caused by: java.io.IOException: Cannot run program "/app/.javacpp/cache/ffmpeg-5.0-1.5.7-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/ffmpeg": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at net.bramp.ffmpeg.RunProcessFunction.run(RunProcessFunction.java:39)
	at net.bramp.ffmpeg.FFcommon.version(FFcommon.java:66)
	at net.bramp.ffmpeg.FFmpeg.version(FFmpeg.java:31)
	at net.bramp.ffmpeg.FFmpeg.<init>(FFmpeg.java:90)
	at net.bramp.ffmpeg.FFmpeg.<init>(FFmpeg.java:85)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 82 common frames omitted

I have a functionality to deal with audio/video files and from the logs I could see that it is failing while loading and creating **ffmpeg** class.

Below are the list of ffmpeg related dependency I am passing through the pom.xml file.
**pom.xml**
                <dependency>
			<groupId>net.bramp.ffmpeg</groupId>
			<artifactId>ffmpeg</artifactId>
			<version>0.6.2</version>
		</dependency>

		<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>ffmpeg</artifactId>
			<version>5.0-1.5.7</version>
		</dependency>

		<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>javacpp</artifactId>
			<version>1.5.7</version>
		</dependency>

		<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>ffmpeg</artifactId>
			<version>5.0-1.5.7</version>
			<classifier>linux-x86</classifier>
		</dependency>

		<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>ffmpeg</artifactId>
			<version>5.0-1.5.7</version>
			<classifier>windows-x86_64</classifier>
		</dependency>

		<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>ffmpeg-platform</artifactId>
			<version>5.0-1.5.7</version>
		</dependency>
		
		
Any help will be greatly appreciated.

**Comment by saudet** [comment]
Please set the "org.bytedeco.javacpp.logger.debug" system property to "true" to get more information on the console.

**Comment by saudet** [comment]
Duplicate of https://github.com/bytedeco/javacpp-presets/issues/1379
