### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: library "libjniopenblas_nolapack.so" not found

### ISSUE THREAD

**Issue by Manishinfo22** [bytedeco/javacpp#640]
I am trying to read the image using the function cvLoadImage() my application is getting crash and throwing an error.

`
 java.lang.UnsatisfiedLinkError: dlopen failed: library "libjniopenblas_nolapack.so" not found
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1661)
                                                                                                    	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1825)
                                                                                                    	at org.bytedeco.javacpp.Loader.load(Loader.java:1416)
                                                                                                    	at org.bytedeco.javacpp.Loader.load(Loader.java:1227)
                                                                                                    	at org.bytedeco.javacpp.Loader.load(Loader.java:1203)
                                                                                                    	at org.bytedeco.openblas.global.openblas_nolapack.<clinit>(openblas_nolapack.java:12)
                                                                                                    	at java.lang.Class.classForName(Native Method)
                                                                                                    	at java.lang.Class.forName(Class.java:454)
                                                                                                    	at org.bytedeco.javacpp.Loader.load(Loader.java:1282)
                                                                                                    	at org.bytedeco.javacpp.Loader.load(Loader.java:1227)
                                                                                                    	at org.bytedeco.javacpp.Loader.load(Loader.java:1203)
                                                                                                    	at org.bytedeco.opencv.opencv_core.AbstractArray.<clinit>(AbstractArray.java:18)
                                                                                                    	at org.bytedeco.opencv.helper.opencv_imgcodecs.cvLoadImage(opencv_imgcodecs.java:37)
                                                                                                    	at org.bytedeco.opencv.helper.opencv_imgcodecs.cvLoadImage(opencv_imgcodecs.java:34)`

**Comment by saudet** [comment]
How are you trying to use the JAR files?

**Comment by saudet** [comment]
In any case, you'll need to add all the JAR files in your class path, and then this will work.
