### ISSUE TITLE
Cannot find the .so file when running the jar package.

### ISSUE THREAD

**Issue by mengpengfei** [bytedeco/javacpp#690]
The error message can be seen in one image.  
![image](https://github.com/bytedeco/javacpp/assets/13211758/48b9ae5e-7f46-4ef3-aa94-e639c1d37159)
After I manually copied the libopencv_world.so.3.4 file over, the program ran normally.

However, the libopencv_world.so.3.4 file is already included in the jar package.
Why wasn't the libopencv_world.so.3.4 file extracted to that directory, causing me to manually copy the file over when running the program?

I have tested all versions of javacpp, but this issue still remains unsolved.
Is there any way to solve this problem?

**Comment by mengpengfei** [comment]
![image](https://github.com/bytedeco/javacpp/assets/13211758/e222a7b4-e7d6-45fb-beb1-f1861fcda146)
From the above picture, it can be seen that the jar package already contains the so file.
Except for the file libopencv_world.so.3.4, the other two .so files were successfully extracted to the path /root/.javacpp/cache/yolo-api-1.0-jar-with-dependencies.jar/***/****/***/linux-x86_64.

**Comment by saudet** [comment]
You should ask the author of that YoloApi project. I don't know anything about it.

**Comment by saudet** [comment]
Please set the "org.bytedeco.javacpp.logger.debug" system property to "true" to get more information on the console.

**Comment by mengpengfei** [comment]
Does it have anything to do with the caching function of javacpp? Some .so files will not be cached.

**Comment by mengpengfei** [comment]
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.javacpp.Loader
Debug: Loading /root/.javacpp/cache/yolo-api-1.0-jar-with-dependencies.jar/org/bytedeco/javacpp/linux-x86_64/libjnijavacpp.so
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.javacpp.Pointer
Debug: Loading class top.**.yolo.YoloApi
Debug: Loading /root/.javacpp/cache/yolo-api-1.0-jar-with-dependencies.jar/top/**/yolo/linux-x86_64/libdarknet.so
Debug: Failed to load /root/.javacpp/cache/yolo-api-1.0-jar-with-dependencies.jar/top/**/yolo/linux-x86_64/libdarknet.so: java.lang.UnsatisfiedLinkError: /root/.javacpp/cache/yolo-api-1.0-jar-with-dependencies.jar/top/**/yolo/linux-x86_64/libdarknet.so: libopencv_world.so.3.4: cannot open shared object file: No such file or directory

> Please set the "org.bytedeco.javacpp.logger.debug" system property to "true" to get more information on the console.

**Comment by mengpengfei** [comment]
Debug: Loading library darknet
Debug: Failed to load for darknet: java.lang.UnsatisfiedLinkError: no darknet in java.library.path
Debug: Loading /root/.javacpp/cache/yolo-api-1.0-jar-with-dependencies.jar/top/**/yolo/linux-x86_64/libjniYoloApi.so
Debug: Failed to load /root/.javacpp/cache/yolo-api-1.0-jar-with-dependencies.jar/top/**/yolo/linux-x86_64/libjniYoloApi.so: java.lang.UnsatisfiedLinkError: /root/.javacpp/cache/yolo-api-1.0-jar-with-dependencies.jar/top/**/yolo/linux-x86_64/libjniYoloApi.so: libopencv_world.so.3.4: cannot open shared object file: No such file or directory
Debug: Loading library jniYoloApi
Debug: Failed to load for jniYoloApi: java.lang.UnsatisfiedLinkError: no jniYoloApi in java.library.path

**Comment by saudet** [comment]
It doesn't look like that YoloApi was designed to extract that library. Please report downstream.

**Comment by mengpengfei** [comment]
These codes were written by me alone, and the jar package was generated using a Maven plugin. Below is the configuration file information for Maven.
    <dependencies>
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacpp</artifactId>
            <version>1.5.9</version>
            <classifier>linux-x86_64</classifier>
        </dependency>
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacpp</artifactId>
            <version>1.5.9</version>
        </dependency>
    </dependencies>
    <build>
        <resources>

            <resource>

                <directory>src/main/java</directory>

                <includes>
                    <include>**/*.so*</include>
                </includes>
              
                <filtering>false</filtering>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifest>
                            <mainClass></mainClass>
                        </manifest>
                    </archive>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                </configuration>
                <executions>
                    <execution>
                        <id>make-assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

**Comment by mengpengfei** [comment]
I write code independently without any upstream or downstream.

**Comment by saudet** [comment]
So, try to add  "opencv_world@.3.4" to the `@Platform(link=...` annotation value as shown here:
https://github.com/bytedeco/javacpp-presets/wiki/Create-New-Presets

**Comment by mengpengfei** [comment]
![image](https://github.com/bytedeco/javacpp/assets/13211758/27f3ecad-7148-4ffc-9113-f831d90ef0b8)

**Comment by mengpengfei** [comment]
Still printed the same error.

> So, try to add "opencv_world@.3.4" to the `@Platform(link=...` annotation value as shown here: https://github.com/bytedeco/javacpp-presets/wiki/Create-New-Presets

**Comment by saudet** [comment]
Please set the "org.bytedeco.javacpp.logger.debug" system property to "true" to get more information on the console.

**Comment by mengpengfei** [comment]
![image](https://github.com/bytedeco/javacpp/assets/13211758/9e829dc7-7b7e-46cd-9568-2105a1e3aeac)
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.javacpp.Loader
Debug: Loading /root/.javacpp/cache/yolo-api-1.0-jar-with-dependencies.jar/org/bytedeco/javacpp/linux-x86_64/libjnijavacpp.so
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.javacpp.Pointer
Debug: Loading class top.dg.yolo.YoloApi
Debug: Loading library opencv_world.so.3.4
Debug: Failed to load for opencv_world.so.3.4: java.lang.UnsatisfiedLinkError: no opencv_world.so.3.4 in java.library.path
Debug: Loading /root/.javacpp/cache/yolo-api-1.0-jar-with-dependencies.jar/top/dg/yolo/linux-x86_64/libdarknet.so
Debug: Failed to load /root/.javacpp/cache/yolo-api-1.0-jar-with-dependencies.jar/top/dg/yolo/linux-x86_64/libdarknet.so: java.lang.UnsatisfiedLinkError: /root/.javacpp/cache/yolo-api-1.0-jar-with-dependencies.jar/top/dg/yolo/linux-x86_64/libdarknet.so: libopencv_world.so.3.4: cannot open shared object file: No such file or directory
Debug: Loading library darknet
Debug: Failed to load for darknet: java.lang.UnsatisfiedLinkError: no darknet in java.library.path
Debug: Loading /root/.javacpp/cache/yolo-api-1.0-jar-with-dependencies.jar/top/dg/yolo/linux-x86_64/libjniYoloApi.so
Debug: Failed to load /root/.javacpp/cache/yolo-api-1.0-jar-with-dependencies.jar/top/dg/yolo/linux-x86_64/libjniYoloApi.so: java.lang.UnsatisfiedLinkError: /root/.javacpp/cache/yolo-api-1.0-jar-with-dependencies.jar/top/dg/yolo/linux-x86_64/libjniYoloApi.so: libopencv_world.so.3.4: cannot open shared object file: No such file or directory
Debug: Loading library jniYoloApi
Debug: Failed to load for jniYoloApi: java.lang.UnsatisfiedLinkError: no jniYoloApi in java.library.path
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniYoloApi in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
        at java.lang.Runtime.loadLibrary0(Runtime.java:871)
        at java.lang.System.loadLibrary(System.java:1122)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1832)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1423)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1234)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1210)
        at top.dg.yolo.YoloApi.<clinit>(YoloApi.java:10)
        at top.dg.yolo.YoloTest.main(YoloTest.java:22)
Caused by: java.lang.UnsatisfiedLinkError: /root/.javacpp/cache/yolo-api-1.0-jar-with-dependencies.jar/top/dg/yolo/linux-x86_64/libjniYoloApi.so: libopencv_world.so.3.4: cannot open shared object file: No such file or directory
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)
        at java.lang.Runtime.load0(Runtime.java:810)
        at java.lang.System.load(System.java:1086)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1779)
        ... 5 more

> Please set the "org.bytedeco.javacpp.logger.debug" system property to "true" to get more information on the console.

**Comment by mengpengfei** [comment]
It  is ok now！ thanks very much！
I'm curious about the principle behind this setting. Is there any documentation available?

**Comment by saudet** [comment]
The `@Platform` annotation? Sure, there's a bit here: http://bytedeco.org/javacpp/apidocs/org/bytedeco/javacpp/annotation/Platform.html
