### ISSUE TITLE
windows   Cannot run program "cl"

### ISSUE THREAD

**Issue by shuaidan0412** [bytedeco/javacpp#716]
env:
windows10   22H2
mingw64
visual stdio 2022
cl path:   C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64

1.  if not add cl path to system path
 error:   Cannot run program "cl"

2. if add cl path to system path
error:

jniTest.cpp
C:\Program Files\Java\jdk1.8.0_181\include\jni.h(39): fatal error C1083: 无法打开包括文件: “stdio.h”: No such file or directory
jnijavacpp.cpp
C:\Program Files\Java\jdk1.8.0_181\include\jni.h(39): fatal error C1083: 无法打开包括文件: “stdio.h”: No such file or directory
Exception in thread "main" java.lang.RuntimeException: Process exited with an error: 2
        at org.bytedeco.javacpp.tools.Builder.generateAndCompile(Builder.java:620)
        at org.bytedeco.javacpp.tools.Builder.build(Builder.java:1167)
        at org.bytedeco.javacpp.tools.Builder.main(Builder.java:1450)

**Comment by saudet** [comment]
Please try to follow instructions:
https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments#windows-x86-and-x86_64
