### ISSUE TITLE
typed enum support

### ISSUE THREAD

**Issue by ashleyj** [bytedeco/javacpp#78]
Currently there's no support for typed c++ enums
eg.

```
namespace clang {

/// \brief Specifies which overload candidates to display when overload
/// resolution fails.
enum OverloadsShown : unsigned {
  Ovl_All,  ///< Show all overloads.
  Ovl_Best  ///< Show just the "best" overload candidates.
};

```

Parsing such an enum generates the following:

```
Caused by: org.bytedeco.javacpp.tools.ParserException: /Users/ash/src/javacpp-presets/llvm/cppbuild/macosx-x86_64/include/clang/Basic/DiagnosticOptions.h:23: Unexpected token 'unsigned'
        at org.bytedeco.javacpp.tools.Token.expect(Token.java:99)
        at org.bytedeco.javacpp.tools.Parser.declarator(Parser.java:826)
        at org.bytedeco.javacpp.tools.Parser.function(Parser.java:1443)
        at org.bytedeco.javacpp.tools.Parser.declarations(Parser.java:2600)
        at org.bytedeco.javacpp.tools.Parser.namespace(Parser.java:2506)
        at org.bytedeco.javacpp.tools.Parser.declarations(Parser.java:2598)
        at org.bytedeco.javacpp.tools.Parser.parse(Parser.java:2674)
        at org.bytedeco.javacpp.tools.Parser.parse(Parser.java:2767)
        at org.bytedeco.javacpp.tools.Builder.parse(Builder.java:68)
        at org.bytedeco.javacpp.tools.Builder.build(Builder.java:620)
        at org.bytedeco.javacpp.tools.BuildMojo.execute(BuildMojo.java:225)

```

**Comment by saudet** [comment]
Should work now! Let me know how it goes.

**Comment by ashleyj** [comment]
Good good, no longer erroring on that header, but it's choking on the following block. Seems related to the lack of brackets in the enum declaration.

```
namespace sys {
namespace fs {
enum OpenFlags : unsigned; 
}
}
```

source: llvm/cppbuild/macosx-x86_64/include/llvm/Support/raw_ostream.h - line 38


ST
```

Caused by: org.bytedeco.javacpp.tools.ParserException: /Users/ash/src/javacpp-presets/llvm/cppbuild/macosx-x86_64/include/llvm/Support/raw_ostream.h
:30: Unexpected token 'unsigned'
        at org.bytedeco.javacpp.tools.Token.expect(Token.java:99)
        at org.bytedeco.javacpp.tools.Parser.declarator(Parser.java:840)
        at org.bytedeco.javacpp.tools.Parser.function(Parser.java:1457)
        at org.bytedeco.javacpp.tools.Parser.declarations(Parser.java:2629)
        at org.bytedeco.javacpp.tools.Parser.namespace(Parser.java:2534)
        at org.bytedeco.javacpp.tools.Parser.declarations(Parser.java:2627)
        at org.bytedeco.javacpp.tools.Parser.namespace(Parser.java:2534)
        at org.bytedeco.javacpp.tools.Parser.declarations(Parser.java:2627)
        at org.bytedeco.javacpp.tools.Parser.namespace(Parser.java:2534)
        at org.bytedeco.javacpp.tools.Parser.declarations(Parser.java:2627)
        at org.bytedeco.javacpp.tools.Parser.parse(Parser.java:2703)
        at org.bytedeco.javacpp.tools.Parser.parse(Parser.java:2796)
        at org.bytedeco.javacpp.tools.Builder.parse(Builder.java:69)
        at org.bytedeco.javacpp.tools.Builder.build(Builder.java:625)
        at org.bytedeco.javacpp.tools.BuildMojo.execute(BuildMojo.java:226)
```

Technically not related, so happy to open a new issue if you'd like

**Comment by saudet** [comment]
They have a strange way of using enum... Anyway, I've fixed that too! Thanks for reporting.

**Comment by ashleyj** [comment]
Thanks for the speedy fix :)
